### PR TITLE
LF-4226: Clear filters on reset

### PR DESCRIPTION
**Pull request by zagran**
**Description**

Clear filter options, previously default value was used.

Jira link: https://lite-farm.atlassian.net/browse/LF-4226

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Thanks @zagran for taking a look here!

Reading the Jira ticket , I think what I was expecting was that when the user "clears all" filters that it returns to the default state of "all selected" instead of "none selected". 

Its an awkward state because we want them all to be selected but not show the individual pills unless interacted with.

**Comment by zagran** [comment]
> Thanks @zagran for taking a look here!
> 
> 
> 
> Reading the Jira ticket , I think what I was expecting was that when the user "clears all" filters that it returns to the default state of "all selected" instead of "none selected". 
> 
> 
> 
> Its an awkward state because we want them all to be selected but not show the individual pills unless interacted with.
> 
> 
> 
> 
> 
> 

I'll fix it then. Thank you for watching 

Do I need to change something in the code? Since this is my first contribution, the code may not be perfect (or even not correct at all) - I don't want to add more mess or workarounds

**Comment by Duncan-Brain** [comment]
I think yes the code should be corrected. I can do the request changes button haha but most times I do not use it unless I know what to change.

**Review by Duncan-Brain — CHANGES_REQUESTED** [review]
"All" should be selected when cleared. But no pills should be present.

**Comment by zagran** [comment]
Returning this ticket to TODO. I do not understand the final requirements.

**Pull request closed without merging**
