### PR TITLE
LF-4373  Locked Input

### PR DESCRIPTION
**Pull request by Tbrid**
**Description**

Added new locked variant of input: specified by a boolean value prop in the Input component. When locked is true, input is also disabled.

Jira link: https://lite-farm.atlassian.net/browse/LF-4377

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by antsgar** [comment]
@Tbrid thank you so much for your contribution! I tried the new prop in one of the inputs in our Animals form and see a gap above the input that seems to be caused by the div containing the icon

Screenshot 2024-09-19 at 4 31 54 PM

Beyond that styling issue in particular, I spent a bit of time looking at our input components, and it seems the current `Input` has a lot of stale code and would need some refactoring down the line. The bulk of the code that's still useful from it also lives in `InputBase` which in turn is used as the base component for all the different inputs we're seeing in new screens. So basically the most recent pattern is we reuse this `InputBase` component and extend it for different use cases. In this case, we could create a `LockedInput` component based on `InputBase`. To see the pattern I'm referring to in action, take a look at the `NumberInput` component or at this PR https://github.com/LiteFarmOrg/LiteFarm/pull/3096. You'd use the `rightSection` prop in `InputBase` to display the locked icon. Eventually, the `Input` component would be deprecated in favor of this new pattern.

If you have some time, I think it'd be good to move towards this pattern for this PR as well -- I understand that it wasn't specified in the ticket though, so if it's not possible it's okay as long as we fix the styling issue pointed above.

I'm thinking the best path moving forward would be to add a deprecated flag to `Input` and a comment pointing towards this new pattern so it's easier to figure out in the future -- as well of course as a tech debt ticket for migrating away from `Input` altogether if we don't have one already.

**Comment by Tbrid** [comment]
> @Tbrid thank you so much for your contribution! I tried the new prop in one of the inputs in our Animals form and see a gap above the input that seems to be caused by the div containing the icon
> 
> Screenshot 2024-09-19 at 4 31 54 PM
> Beyond that styling issue in particular, I spent a bit of time looking at our input components, and it seems the current `Input` has a lot of stale code and would need some refactoring down the line. The bulk of the code that's still useful from it also lives in `InputBase` which in turn is used as the base component for all the different inputs we're seeing in new screens. So basically the most recent pattern is we reuse this `InputBase` component and extend it for different use cases. In this case, we could create a `LockedInput` component based on `InputBase`. To see the pattern I'm referring to in action, take a look at the `NumberInput` component or at this PR #3096. You'd use the `rightSection` prop in `InputBase` to display the locked icon. Eventually, the `Input` component would be deprecated in favor of this new pattern.
> 
> If you have some time, I think it'd be good to move towards this pattern for this PR as well -- I understand that it wasn't specified in the ticket though, so if it's not possible it's okay as long as we fix the styling issue pointed above.
> 
> I'm thinking the best path moving forward would be to add a deprecated flag to `Input` and a comment pointing towards this new pattern so it's easier to figure out in the future -- as well of course as a tech debt ticket for migrating away from `Input` altogether if we don't have one already.

Ok, I will try using the new pattern.

**Review by antsgar — APPROVED** [review]
Looks great! 🎉 🚀 thank you for your contribution 😄

**Comment by Duncan-Brain** [comment]
Looks great thanks for using the new pattern! 

Wondering if you also see the white background behind the Icon? 
Screenshot 2024-09-23 at 4 05 41 PM

**Comment by Tbrid** [comment]
> Looks great thanks for using the new pattern!
> 
> Wondering if you also see the white background behind the Icon? Screenshot 2024-09-23 at 4 05 41 PM

Turned bg color to be transaparent.

**Review by Duncan-Brain — APPROVED** [review]
Thank you, seems fixed to me!

**Pull request merged**
