### PR TITLE
Fixed map update for sensors

### PR DESCRIPTION
**Pull request by Cali0707**
This PR makes the map update to show newly updated sensors on both a full success and a partial success. It also resolves  a small bug described in the comments on https://lite-farm.atlassian.net/browse/LF-2645 

To test:
1. Upload a file with one ESID which is claimed on another farm and one which is free - you should get one sensor added to your map, and a valid error message.
2. Unclaim the ESID which is claimed on another farm and upload the file again - you should be able to see both sensors on the farm map now

### CODE REVIEW

**Review by AbdusShaikh — CHANGES_REQUESTED** [review]
Sensors are uploaed correctly but sometimes do not show up on the map without refreshing

**Comment by Cali0707** [comment]
@AbdusShaikh I believe this should be fixed with my latest commit

**Review by anant00729 — APPROVED** [review]
Looks good to me. After sensor upload, the new sensor get added/plotted on the farm map.

**Review by fsayyid — APPROVED** [review]
This is working well for me, good work!

**Comment by fsayyid** [comment]
@AbdusShaikh can you approve this PR? I can't merge since you requested changes.

**Review by AbdusShaikh — APPROVED** [review]

**Pull request merged**
