### PR TITLE
fix: moment not found

### PR DESCRIPTION
**Pull request by liao02x**
**Description**

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

`moment` lib is used in `packages/api` but is not listed as a dependency. This pr adds it to the dependencies. No new files added.
To reproduce, remove `node_modules` folder under `packages/api`, run `pnpm i` then `pnpm start` and the error shows up.

Jira link:

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

After adding `moment` to the dependencies, running `pnpm start` wouldn't show the error again.

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Hi @liao02x . 

Thank you for this PR we really appreciate you pointing this out!  

One question: Do you run into the same issue if you run `npm i` ?

I was trying to figure out why I didn't have this problem myself and @SayakaOno pointed out that we only actually use pnpm on the frontend. Which I totally forgot about. 

Not sure why we have pnpm-lock in /api.

**Comment by liao02x** [comment]
Hi @Duncan-Brain .

I actually tried `npm i` first and it shows a conflict issue on my side, which is why I thought you guys are switching to pnpm and keeping the package.lock file for some reason.

The error I got on my side:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: objection@2.2.17
npm ERR! Found: knex@0.95.15
npm ERR! node_modules/knex
npm ERR!   knex@"^0.95.15" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"<0.95.0" from objection@2.2.17
npm ERR! node_modules/objection
npm ERR!   objection@"^2.2.16" from the root project
npm ERR!   peer objection@">= 0.8" from objection-soft-delete@1.0.7
npm ERR!   node_modules/objection-soft-delete
npm ERR!     objection-soft-delete@"^1.0.7" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: knex@0.21.21
npm ERR! node_modules/knex
npm ERR!   peer knex@"<0.95.0" from objection@2.2.17
npm ERR!   node_modules/objection
npm ERR!     objection@"^2.2.16" from the root project
npm ERR!     peer objection@">= 0.8" from objection-soft-delete@1.0.7
npm ERR!     node_modules/objection-soft-delete
npm ERR!       objection-soft-delete@"^1.0.7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/mitch/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mitch/.npm/_logs/2023-03-03T19_51_20_197Z-debug-0.log
```

Reproduce:
remove the `packages/api/node_modules` folder, or clone the repo to a new workplace, then `npm i` under `packages/api`

**Comment by JimmyRowland** [comment]
@liao02x thanks for pointing this out.
I also had the same conflict. npm is notorious for package resolution issues.
The plan was to migrate to pnpm but the previous team decided to set the node version to 16.15.0 as a walk-around for some reason.

The conflict issue should be gone when https://nodejs.org/en/blog/release/v19.6.0/ is merged into stable release and the app is migrated to node 20.

**Review by Duncan-Brain — CHANGES_REQUESTED** [review]
Looks good to me, I think we would just want the package-lock as well since we use npm on the api side.

Hopefully in the future we can take Jimmy's advice and just switch back to npm for the entire project now that it has pnpm functionality.

**Comment by JimmyRowland** [comment]
Agree. Pnpm lock file shouldn't be in API folder

**Pull request closed without merging**
