### PR TITLE
Fixed bug where it was impossible to invite a pseudo user

### PR DESCRIPTION
**Pull request by Cali0707**
This PR resolves the issue described in the comments of https://lite-farm.atlassian.net/browse/LF-2672

To test:
1. Try and invite a pseudo user
2. This should work
3. Try and invite a non pseudo user using an email of an existing user on the farm
4. You should be shown an inline error

### CODE REVIEW

**Comment by seinnlee** [comment]
@Cali0707 Why do we not get an inline error for inviting a worker with an email that's already associated with another account on the farm?

**Comment by seinnlee** [comment]
@Cali0707 It's not the cleanest but something like this would solve the issue Mwaya found but also show inline error if the email already exists when inviting a farm worker.

`return ((((role.value === 3) ? true : value) && !userFarmEmails.includes(value.toLowerCase())) ||
                t('INVITE_USER.ALREADY_EXISTING_EMAIL_ERROR'));`

**Comment by Cali0707** [comment]
@seinnlee good catch! I've fixed this now

**Review by seinnlee — APPROVED** [review]
LGTM!

**Review by jagDhillon077 — APPROVED** [review]
This works for me 👍🏽

**Pull request merged**
