### PR TITLE
LF-2758 export server cicd

### PR DESCRIPTION
**Pull request by craigyu**
**Description**

This PR has 3 changes: 
1. Added a `script_stop` function. This will stop script after the first failure, and the job will show as failed. In the previous version, if for example, the `git pull` step fails, it will still run the rest of the script and we will see a green check mark thinking the job has been completed. 
2. Instead of restarting the service, it deletes the service then starts it again, in case there isn't any service to restart.
3. Exposed our deployment script for easy management, since there is little reason to hide the script.  

Jira link: [LF-2758](https://lite-farm.atlassian.net/browse/LF-2758?atlOrigin=eyJpIjoiMWJkMGY1ZTgzMjkyNDliZGFiYTA3MDU3ZWY4ZGI5MTIiLCJwIjoiaiJ9)

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [x] Other (please explain)
    - Tested with github action. See the output [here](https://github.com/LiteFarmOrg/LiteFarm/actions/runs/4349449956/jobs/7599134530).

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-2758]: https://lite-farm.atlassian.net/browse/LF-2758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by craigyu** [comment]
Some explanation of the script:
the ```git add -A .  &  git stash``` are there to prevent this error: 
image

the `export NVM_DIR=~/.nvm &
source ~/.nvm/nvm.sh` are there to prevent the `nvm not found` error, the solution was found [here](https://github.com/appleboy/ssh-action/issues/21#issuecomment-574050424).

**Review by Duncan-Brain — APPROVED** [review]
@craigyu  

Sorry it took so long to review but looks good to me!

**Comment by iperdomo** [comment]
I would suggest to move away from having shell scripts embedded in yaml files. Having an actual file (`.sh`) means that you can take advantage of your editor, syntax highlighting and linting (via [ShellCheck](https://github.com/koalaman/shellcheck))

**Comment by kathyavini** [comment]
@iperdomo I can open a new PR for that change if we want to merge this first initially (I think @craigyu is quite busy at his new job these days!)

**Pull request merged**
