### PR TITLE
seed development db

### PR DESCRIPTION
**Pull request by JimmyRowland**

### CODE REVIEW

**Comment by smattingly** [comment]
This overlaps with my PR #1654. My PR also includes some migration changes needed to correctly populate the database. @JimmyRowland is it OK to close this in favor of my PR? I can add your good idea of seeding in development only.

**Review by beetai — APPROVED** [review]

**Comment by JimmyRowland** [comment]
#1656

**Comment by JimmyRowland** [comment]
#1656

**Comment by JimmyRowland** [comment]
Resolves #1393

**Pull request merged**
