### PR TITLE
Backport Patch 3.6.5

### PR DESCRIPTION
**Pull request by SayakaOno**
Backport Patch 3.6.5

### CODE REVIEW

**Review by Duncan-Brain — APPROVED** [review]
LGTB!

**Review by kathyavini — DISMISSED** [review]
❤️ ❤️ ❤️

**Review by kathyavini — APPROVED** [review]
Thank you for writing the lint test!

**Comment by Duncan-Brain** [comment]
NLGTB!

**Review by Duncan-Brain — APPROVED** [review]

**Pull request merged**
