### PR TITLE
Feature/ensemble communications webhook auth

### PR DESCRIPTION
**Pull request by jagDhillon077**
Added sensor secret to environment and added it to webhook authorization header. Updated .env default

### CODE REVIEW

**Review by fsayyid — APPROVED** [review]
The webhook registration is still working on my end.

**Review by fsayyid — CHANGES_REQUESTED** [review]
Actually, on further thinking, I am realizing that we need to handle this authorization at the add_reading endpoint. Because right now the header is being added, but we are not checking for it.

**Comment by smattingly** [comment]
@jagDhillon077 @fsayyid I'm confused about the plans for this PR. I'm ready to merge it as is. Should I do that, or are more changes expected?

**Comment by fsayyid** [comment]
I think that's up to how Jag wants to handle my above comment. @jagDhillon077 do you want to add those changes in this PR or another PR?

**Review by smattingly — APPROVED** [review]

**Pull request merged**
