### PR TITLE
LF-4405: floating menu button looks different from what is designed

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

Screenshot 2024-08-29 at 3 22 24 PM

- Fix the position of the floating menu by adjusting the `anchorRef`.
- Implement the active state of the button as designed.
   - replace hex with `var`.
   - switch CSS for hover style and active style so that hover style won't override the active state CSS. 
   - sorry for the formatting!

Screenshot 2024-08-30 at 13 28 00

Jira link: https://lite-farm.atlassian.net/browse/LF-4405

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Careful eye! I never would have noticed this. 

Looking at the figma I am seeing a margin or spacing between the button and the menu on desktop only. I bet that is a mistake in figma and they should be the same. Do you know which is correct?

Figma - desktop
Screenshot 2024-08-30 at 1 09 41 PM

Local - desktop

Screenshot 2024-08-30 at 1 09 11 PM

**Comment by kathyavini** [comment]
Oh dear, there really is some inconsistency in that [Desktop design](https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=3735-40055&m=dev) you found @Duncan-Brain.

I see also that the mobile and component design show the active state without any shadow, but the desktop design has retained it; I suspect that's an error as well (because it's not on the component Figma even for desktop).

I do think the requirement for the inner text area to have some amount of border radius is consistent through all the animal views, though.

If the curved corners are added to the `.menuItem` here, it will also back-propagate to finances, but I think that's OK as this is the more recent version of `<FloatingMenu />`:

Screenshot 2024-08-30 at 11 00 18 AM
Screenshot 2024-08-30 at 11 00 28 AM

**Comment by SayakaOno** [comment]
I should've been more careful when I created it, sorry...

https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=91-14447&m=dev
Screenshot 2024-08-30 at 2 24 27 PM

https://www.figma.com/design/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?node-id=3093-39506&node-type=INSTANCE&m=dev
Screenshot 2024-08-30 at 2 24 41 PM

I think no spacing between the menu and the button is correct.

Also, font-weight was 700 on the finance screen 😅 
Do you mind confirming what's right with Loïc? 🙏 

I will remove the shadow for the active state!

**Comment by kathyavini** [comment]
@SayakaOno 

> Do you mind confirming what's right with Loïc? 🙏

Alright, will do. We can ask Loïc about the font-weight and the desktop spacing. Should we confirm about the border-radius too? I'd be surprised if he didn't want it on animals (it's in all the views) but we can check about what he wants on Finances.

**Comment by SayakaOno** [comment]
Yes, it would be great if you could check those three points. Thank you! 🙏

**Review by kathyavini — APPROVED** [review]

**Review by Duncan-Brain — APPROVED** [review]
Looks good to me! Thanks for aligning the style!

**Pull request merged**
