### PR TITLE
LF-2798-select-the-task-location

### PR DESCRIPTION
**Pull request by Duncan-Brain**
To Test Manually:
- Irrigation task is not completed but by changing Line 28 - isMulti={false} you should observe that multi select is disabled and that only crop enabled areas are visible.

My Concerns:
I had trouble determining the usefulness of readOnlyPinCoordinates and so am unsure if this should be something that is avoided/maintained for this case.

https://lite-farm.atlassian.net/jira/software/c/projects/LF/issues/LF-2798

### CODE REVIEW

**Comment by wasswarichard** [comment]
@Duncan-Brain refactor code to a more readable format.
`  const isHarvestLocation = useIsTaskType('HARVEST_TASK') ;
  const isIrrigationLocation = useIsTaskType('IRRIGATION_TASK');
  const isTransplantLocation = useIsTaskType('TRANSPLANT_TASK');

  if(isHarvestLocation || isIrrigationLocation)
    return <TaskActiveAndPlannedCropLocations history={history} location={location} isMulti={isHarvestLocation}/>;

  if(isTransplantLocation)
    return <TaskTransplantLocations history={history} location={location} />;

  return <TaskAllLocations history={history} location={location} />;`

**Comment by anant00729** [comment]
I ll start my review after @wasswarichard approves the PR.

**Comment by Duncan-Brain** [comment]
Thanks @wasswarichard that's a concise suggestion very nice. Change made.

**Comment by wasswarichard** [comment]
@Duncan-Brain avoid nested if statements. keep it as a single if statement with the return value. See the screenshot in the first comment

**Comment by Duncan-Brain** [comment]
@wasswarichard Ah sorry I missed that! Removing the existing else's thanks for the reminder with that. Done

**Comment by anant00729** [comment]
Reviewed code. it looks good to me. The functionality till the selection of crop field works well.

**Review by anant00729 — APPROVED** [review]

**Review by wasswarichard — APPROVED** [review]

**Comment by anant00729** [comment]
@Duncan-Brain could you please take a sync of integration?

**Comment by Duncan-Brain** [comment]
Closing this I messed up by rebasing I think.

**Pull request closed without merging**
