### PR TITLE
Lf 4304 deleting a soil amendment task throws an error page

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

Fixes task type error shown in a few areas around app.

Jira link: [LF-4304](https://lite-farm.atlassian.net/browse/LF-4304)

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain):

Only area I could test was in notifications, @kathyavini if you can test your task with the deleted error that would be swell!

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-4304]: https://lite-farm.atlassian.net/browse/LF-4304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SayakaOno — COMMENTED** [review]
I can't reproduce it even though I created a task with volume, which seems unrelated to the fix...?
I'll come back after Joyce reviews!

**Comment by Duncan-Brain** [comment]
@SayakaOno were you able to recreate the taskType error when you go to notifications, "Take me there".

**Review by SayakaOno — APPROVED** [review]
@Duncan-Brain Yes! I found out what to do, thank you!

**Review by kathyavini — APPROVED** [review]
I don't even remember anymore in which situation deleting a task would route to the task details page (and so crash) as shown in the video, I for sure can't reproduce that myself!

But this works great for the notification crash and I trust the other is resolved as well. Agreed volume seems irrelevant, even though on Friday that was the only way to trigger for me! 😅

**Pull request merged**
