### PR TITLE
LF-3308 - Assign all tasks to one assignee

### PR DESCRIPTION
**Pull request by Tbrid**
**Description**

Feature: Adding ability to assign tasks during plan creation, modified the endpoint of post management plan to assign tasks during creation. 

Jira link: https://lite-farm.atlassian.net/browse/LF-3308

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [x] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by SayakaOno — COMMENTED** [review]
Thank you for taking care of this, it works great!
I wanted `precommit` to be run for code formatting, but it looks like it didn't. (Could you try `npm install` in root directory and see if precommit runs?) I am looking for a way to format the code, and I might ask you to do something later!

**Comment by iperdomo** [comment]
Dear @Tbrid 

As @SayakaOno mentioned there are some files that are not following our formatting rules. Can you please:
- Update your branch with latest changes from `integration`
- Run `prettier --fix` on your modified files?

You can check your changed files with `prettier --check`, e.g.

### `webapp` package
```
$ ./node_modules/.bin/prettier --check public/locales/en/translation.json public/locales/es/translation.json public/locales/fr/translation.json public/locales/pt/translation.json src/components/Crop/ManagementPlanName/index.jsx src/components/Task/AssignTask/index.jsx src/components/Task/AssignTask/useTaskAssignForm.jsx src/containers/Crop/AddManagementPlan/ManagementPlanName/index.jsx
Checking formatting...
[warn] src/components/Task/AssignTask/useTaskAssignForm.jsx
[warn] src/containers/Crop/AddManagementPlan/ManagementPlanName/index.jsx
[warn] Code style issues found in 2 files. Forgot to run Prettier?
``` 
### `api` package
```
$ ./node_modules/.bin/prettier --check src/controllers/managementPlanController.js tests/managementPlan.test.js 
Checking formatting...
[warn] src/controllers/managementPlanController.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?

```

**Review by iperdomo — CHANGES_REQUESTED** [review]
Please format the changed files with `prettier --fix`

**Review by SayakaOno — APPROVED** [review]
Thank you, it looks good!

**Review by iperdomo — APPROVED** [review]

**Pull request merged**
