### PR TITLE
generic drawer component

### PR DESCRIPTION
**Pull request by gursimran-singh**
**Description**

Generic drawer component which opens from bottom with content of desired choice.

Jira link:https://lite-farm.atlassian.net/browse/LF-3751

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

As this is not a standalone component, to test we need to integrate into required part of the app.

- [x] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [x] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by antsgar — DISMISSED** [review]
Tried this out with filtering and it works great, thank you for your contribution! 🎉  I think there'll be a couple of styling adjustments needed to make the contents of the drawer scrollable, but I can add those in on my next PR when I integrate filtering and this one together.

**Review by SayakaOno — COMMENTED** [review]
@gursimran-singh thank you for working on this!

Things I noticed:
- I don't think opacity of the drawer should be 0. It feels a little weird that the content of the main page can be seen through the drawer.
- The overlay colour is too dark?
- The overlay should be above the top bar.


https://github.com/LiteFarmOrg/LiteFarm/assets/33141219/b3685267-b13b-46eb-a5dd-ecbd83f8e42d



@antsgar if you address these above too, I will approve this PR!

**Comment by gursimran-singh** [comment]
@antsgar adjusted css to make drawer scrollable for larger content.
@SayakaOno rectified all the points. Have a look and let me know if any changes are required.

https://github.com/LiteFarmOrg/LiteFarm/assets/22586851/1d083390-8031-430b-bc72-16058cd2d058

**Comment by antsgar** [comment]
Changes look good to me, great work @gursimran-singh!

**Review by antsgar — APPROVED** [review]

**Review by SayakaOno — APPROVED** [review]
Looks great, thank you!

**Pull request merged**
