### PR TITLE
LF-4166 (1): Implement end to end animal creation flow

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

This PR contains the outline of [LF-4166](https://lite-farm.atlassian.net/browse/LF-4166).
It should make the containers tickets easier to be worked on.

- Add `<FloatingButtonMenu />` (Add animals button) to `<Inventory />`
- Update `MultiStepForm` component
  - [Stories](http://localhost:6006/?path=/docs/components-multistepform--docs)
  - Handle different types of variant (`PAGE_TITLE`, `STEPPER_PROGRESS_BAR`)
  - Add `<FormNavigationButtons />` for the new variant of the form
  - Implement logic for the new variant to:
     - submit the form on the second last page
     - hide the button on the last page
  - Implement logic to show `window.confirm` modal when leaving the form (behaviour is TBD)
- Add dummy containers
- Add `<AddAnimals />` container with the dummy containers and create a route for it

Question:
Should the URL for the page be `/animals/inventory/add_animals`?

Jira link: https://lite-farm.atlassian.net/browse/LF-4166

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [x] I have added "MISSING" for all new language tags to languages I don't speak
- [x] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-4166]: https://lite-farm.atlassian.net/browse/LF-4166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by SayakaOno** [comment]
I've added the previous button, and it's ready for review. Thank you!

**Review by kathyavini — COMMENTED** [review]
Now I have completely fallen in love with the new form setup ❤️  It's very clear and it was so easy to plug the form container into this!!!

My only questions were all basically layout related:

1. I think it's the `<Layout />` component that's applying its own default padding (24px all sides but bottom) that is more than what Figma shows for the Animal Basics view (16px all sides). I'm not too fussed about the difference, but _if_ it's possible it might be nice to let the interior form components handle their own padding? I'm not sure how crucial `<Layout />` is to how the MultiStepForm is laid out. OR, since the progress bar has to be fixed on scroll, maybe FixedHeaderContainer could be used and _its_ styles adjusted? Otherwise I think the padding can we removed from the interior components and we can just live with the 24px vs 16px difference 🙂 
2. The mobile Figma view linked below reminded me that we still need to handle some sort of page title on both mobile and desktop view, is that correct? I don't know if I forgot to make title a prop on the Progress Bar, or felt like it was meant to be added at the same time as the desktop one. Should we make a separate ticket for that?
3. As shown in dev daily we have that annoying tablet view situation with expanded sidebar. I'm not sure if it's the purview of any of the Add Animal tickets but it will be something to fix before release, if it doesn't fix itself once the other layout adjusts are made. Shall we make a fresh ticket if it persists after LF-4166 is completed?



4. The form buttons are overlapping the AddMoreAnimals button on the Animal Basics view 🫤 I think it can be fixed in the containers with bottom padding, but maybe that be controlled by MultiStepForm, since they will all have the floating form buttons? Which do you think is better?

**Review by Duncan-Brain — APPROVED** [review]
Also loving the new form template!

Approving since stories look good and it is not final for this ticket for other small fixes.

**Review by SayakaOno — COMMENTED** [review]
@kathyavini  Thank you so much for pointing out the layout issues, which I totally overlooked! I’ll take a closer look at each point and address them properly.

@Duncan-Brain Thank you!

> For future features should we separate skeleton from final "implement end to end"?

I think it's a good idea!!

-----------------------------

Should we merge this PR to unblocked Joyce's PR? (I'll address the layout issues in a separate PR) Either option works for me!

**Comment by kathyavini** [comment]
> Should we merge this PR to unblocked Joyce's PR? (I'll address the layout issues in a separate PR) Either option works for me!

Sounds good, I'll merge! Although the draft PR is blocked by my not being able to get the breed reset on type change to work, not by this PR 😄

**Review by kathyavini — APPROVED** [review]

**Pull request merged**
