### PR TITLE
Lf 4353 surveystack integration link deprecation patch

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

This adds the new surveystack production links. Originally tested using staging on integration.

Jira link: [LF-4353](https://lite-farm.atlassian.net/browse/LF-4353)

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-4353]: https://lite-farm.atlassian.net/browse/LF-4353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Do i have the right base patch branch?

**Comment by kathyavini** [comment]
> Do i have the right base patch branch?

@Duncan-Brain I don't think so :joy: You could either open a new feature branch off of main, and make the code changes there (you're comparing to the right branch, but your feature branch is integration based), OR keep this integration-based branch but diff to integration, and let @SayakaOno  cherry-pick the merge. I would probably do the second. She might have to fix a merge conflict since integration will be moving from `staging` as base URL and patch branch will have `api` as base URL, but it should be a quick conflict to resolve.

**Comment by SayakaOno** [comment]
I personally like the first option for a cleaner commit history (it will allow us to merge the branch into the patch branch, so we won't lose any commits), but either will work!

**Comment by Duncan-Brain** [comment]
Ah yea lol, gotta brach this branch. lol Silly me

**Comment by Duncan-Brain** [comment]
I don't know which one I went with -- but I kept all commits related to this issue in the order they were commited to integration so that there should hopefully be no backporting conflicts.

**Pull request closed without merging**
