### PR TITLE
LF-4426 update gap

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

Increases the gap between days of week buttons to 24px. 

A couple pics snapped on chrome dev setting of Iphone 14 Pro max

Screenshot 2024-09-18 at 2 10 33 PM

Screenshot 2024-09-18 at 2 11 37 PM

Screenshot 2024-09-18 at 2 12 27 PM

Jira link: [LF-4426](https://lite-farm.atlassian.net/browse/LF-4426)

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-4426]: https://lite-farm.atlassian.net/browse/LF-4426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Yeah I dno. My UI preferences are not so fine tuned! I think I prefer left aligned as discussed and just widening the gap from 8px to 24 px. @loicsans can probably take a look here too if you think its worth discussing for Indic.

**Comment by antsgar** [comment]
Looked at the original PR and this one, I think it looks good right now! A few thoughts:
- I think to prevent it from looking "random" as you mention Joyce when it wraps into two lines, the vertical gap should be slightly wider than the horizontal gap (we discussed a similar situation on the dev design meeting the other day). To achieve this we can use `row-gap` and `column-gap` attributes and set `column-gap` to be say 16px and `row-gap` to be 24px (for example).
- IMO it's okay to have the items be different widths in this case if it's too much effort to make them all the same width.
- Center aligning looks a bit weird to me in full screen in comparison to the rest of the screen which is left aligned.
- Not related to all this spacing discussion, but I think the font color on these items should be darker. The light grey makes it seem they are disabled when they aren't.

But of course this is all UX so Loïc would be the best person to chime in!

**Review by antsgar — APPROVED** [review]

**Comment by Duncan-Brain** [comment]
- I like the row-gap column-gap to make it look better -- only question at that point is the touch/mobile thumb width of ~48?px thing if that is okay or not
- It seemed like there were a bunch of tradeoffs yes
- 👍 
- Good point!

**Comment by kathyavini** [comment]
@antsgar center aligning was never for full screen! Only for mobile view (at xs-breakpoint).

It might all be moot as AI has decided now (as I was translating the new calendar files) that Punjabi + Hindi have one-letter abbreviations for the days after all! I will check with translator 😂

**Review by kathyavini — APPROVED** [review]

**Pull request merged**
