### PR TITLE
LF-3085: Add a linter for translations files

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

I found that some checks are already running against json files in pre-commit. I assumed asking translators to do `npm install` to run pre-commit would not be a good idea and decided to add a github workflow so that we will not be able to merge PRs that have invalid JSON files.

- install [eslint-plugin-json](https://www.npmjs.com/package/eslint-plugin-json)
- update `.eslintrc.json` to use eslint-plugin-json
- create a github workflow

Jira link: https://lite-farm.atlassian.net/browse/LF-3085

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Created PRs with:
- trailing comma
```
{
  ...,
  {
    "TEST": "test",
  }
  ...
}
```
- double commas
```
{
  ...,
  {
    "TEST": "test",,
    "TEST2": "test"
  }
  ...
}
```
- invalid characters (E2809C)
```
{
  ...,
  {
    "TEST": “test”
  }
  ...
}
```
Screenshot 2023-11-30 at 4 54 46 PM

Screenshot 2023-11-30 at 4 55 35 PM

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by SayakaOno** [comment]
Tested from a forked repo, and it worked as expected:
Screenshot 2023-12-04 at 9 46 04 AM

**Review by kathyavini — APPROVED** [review]
Ohhh okay I totally missed the most important part of what you were saying this morning about how it shows a bunch of errors 😄 I didn't catch that it lists all the errors _and_ there is no subsequent auto-fixing capability!

Well it's a great improvement in terms of safety and that's awesome that it works for forks! I'm still curious if it can be bypassed by using the GitHub editor UI, but I think we could also resolve to _never_ do that for translation files in the future 😁

**Comment by SayakaOno** [comment]
Thank you @kathyavini!
I just tried adding invalid JSON from GitHub UI. All checks ran, and the issue was caught if that's what you were wondering!

**Comment by SayakaOno** [comment]
I suggested a change against my PR, committed the change and it triggered the checks... When you resolve conflicts, you make a commit (I think...), so I'm assuming the same thing will happen...🤞

**Review by navDhammu — APPROVED** [review]
Looks good!

**Pull request merged**
