### PR TITLE
Lf 2812 high vulnerability updates

### PR DESCRIPTION
**Pull request by JaxJafinPapau**
**Description**

Used npm to upgrade the packages commit by commit, running tests and pinging the server between updates. Most updates were lower in the dependency tree. If any packages present an undiscovered issue we can roll back by commit.

Jira link: https://lite-farm.atlassian.net/browse/LF-2812

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Ran existing test suite and spun up both FE and BE, was able to visit the application and begin registration process.

- [x] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view - simulated only
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by eighteyes** [comment]
Looks like the `knex` upgrade had some breaking changes and the api parser needs a refactor to adjust for these changes.  Total guess here, I'm new to this codebase, but that is the most likely culprit, imo.

**Review by mickenorlen — CHANGES_REQUESTED** [review]
Hi, sorry. I think i missed something in my testing. I'll try again and get back to you

**Review by mickenorlen — APPROVED** [review]
Thank you for your work on this one. I like your updating strategy!

What I tested:
- Wipe db
- Install new deps
- Run migrations
- Wipe browser data or enter app incognito, create new farm etc
- Click around in most places I know. Try to create a couple of things
- Compare any console errors to beta

Seems good!

**Review by Duncan-Brain — APPROVED** [review]
Seems to be working for me! 

I am still seeing the objection peer dependency issue I was hoping might resolve here too but. It seems not to be breaking anything which is cool!

I was concerned that new migrations would not run or rollback on existing database since the one migration was edited -- but it seemed to work fine!

I also tested InviteToken which seemed to work fine. I could not test notifications since we do not have access to this locally yet. Lets try testing that once merged in to beta!

**Review by Duncan-Brain — APPROVED** [review]
Thanks for this. Node 16.15.0 was required for me to avoid the objection and knex conflict.

**Comment by SayakaOno** [comment]
Thank you Jeremy for this PR. We resolved conflicts and will merge now!

**Pull request merged**
