### PR TITLE
LF 2502 - temperature component UI refinements

### PR DESCRIPTION
**Pull request by anant00729**
To Test,

1. go to http://localhost:3000/sensor/<location_id>/readings. check the nearest station name. dates on the x-axis and try switching from Celsius to Fahrenheit.

For more details, please check: 
https://lite-farm.atlassian.net/browse/LF-2502

### CODE REVIEW

**Comment by anant00729** [comment]
Adding the screenshots: 

Screen Shot 2022-07-22 at 10 14 17 AM

**Comment by fsayyid** [comment]
(No data) and "Ambient temperature for <Weather_Station>" are not being translated.

**Review by fsayyid — CHANGES_REQUESTED** [review]
Otherwise seems to be working, just the one language issue.

**Comment by anant00729** [comment]
@fsayyid Thanks for reviewing it. I have added the requested feedback. Please check.

**Review by fsayyid — APPROVED** [review]

**Review by smattingly — APPROVED** [review]

**Pull request merged**
