### PR TITLE
Invalidate animal tags when movement task is completed

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

Invalidate animal tags when movement task is completed. This will update animals' location immediately on the inventory/animal details view.

### CODE REVIEW

**Review by kathyavini — DISMISSED** [review]
Thank you! I think I saw behaviour and thought it was a bug to investigate later, it didn't occur to me it just needed the invalidation.

I think the merge of Anto's saga change has generated conflicts.

**Review by Duncan-Brain — APPROVED** [review]
Saw this was related to me trying not to do the other invalidation haha. 

I see that because we don't have animalLocations join this is necessary, thanks for doing this. 

I approve (but obv the conflicts)

**Comment by kathyavini** [comment]
>Saw this was related to me trying not to do the other invalidation haha.

@Duncan-Brain hehe I don't think so, that one was for task creation and deletion and this is something I missed on completion PATCH 😁

**Comment by SayakaOno** [comment]
Thank you!
I hope Joyce's PR doesn't get conflicts!

**Review by Duncan-Brain — APPROVED** [review]

**Review by antsgar — APPROVED** [review]

**Pull request merged**
