### PR TITLE
Lf 4387 migrate upload public images functions to new reusable function

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

-80 lines of reused code

This uses the utility instead of storing the same logic in multiple controllers.

To test: Make sure local image bucket is running

Jira link: [LF-4387](https://lite-farm.atlassian.net/browse/LF-4387)

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-4387]: https://lite-farm.atlassian.net/browse/LF-4387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SayakaOno — APPROVED** [review]
Worked as expected :)

**Review by kathyavini — APPROVED** [review]
Mmmm I love it! ❤️ 

Architecturally, is there a reason to prefer defining an empty controller as opposed to puting the function right on the route?

```js
router.post(
  '/upload/farm/:farm_id',
   // ...
  uploadPublicImage('crop'),
);
```
I would have put it on the route to have one less file to click through in order to read what's happening, but is it a bad pattern?

**Comment by LiteFarm-eng** [comment]
@kathyavini 

Interesting point! I do like that -- I didn't think of that, but I think if I were to do it -- I might make the util file into an actual controller like "externalController" or "externalStorageController" and move it there instead of having the route call a util file. it feels like it should always call a controller (or middleware).

**Comment by Duncan-Brain** [comment]
@kathyavini

Interesting point! I do like that -- I didn't think of that, but I think if I were to do it -- I might make the util file into an actual controller like "externalController" or "externalStorageController" and move it there instead of having the route call a util file. it feels like it should always call a controller (or middleware).

**Comment by kathyavini** [comment]
> I might make the util file into an actual controller like "externalController" or "externalStorageController" and move it there instead of having the route call a util file. it feels like it should always call a controller (or middleware).

@Duncan-Brain you are so right and this made me realize belatedly that probably both `fileUpload.js` and `imageUpload.js` probably didn't belong in utils to start with -- they are both middleware/controller format regardless of how they were named or the fact they live alongside non-controller utilities in `utils/` folder 😂  fileUpload.js belongs in `middleware/` and imageUpload.js in `controllers/` I would think. But I don't know about the naming convention for controllers that don't map one-to-one for routes -- that's called `external`?

**Comment by Duncan-Brain** [comment]
I think we can call it whatever. I can't find any suggestions with a quick google search. It could probably be its own route too... lol.

**Pull request merged**
