### PR TITLE
LF-2676

### PR DESCRIPTION
**Pull request by seinnlee**
Ticket LF-2676

### CODE REVIEW

**Comment by Cali0707** [comment]
To test:
1. Create a pseudo user on your farm
2. Invite a user with an email to your farm
3. Try to convert the pseudo user to a normal user with the same email as the existing user - you should get an inline error and not be allowed to make the change

**Review by jagDhillon077 — CHANGES_REQUESTED** [review]
LGTM I got the desired error "A user with that email has access to this farm" 

- just fix merge conflicts

**Review by jagDhillon077 — APPROVED** [review]

**Comment by smattingly** [comment]
@Cali0707 Here is CI log for failing test: 
```
11:05:47]	Summary of all failing tests
[11:05:47]	FAIL tests/userFarm.test.js (5.865 s)
[11:05:47]	  ● User Farm Tests › Update user farm: authorization tests › Invite pseudo user test › Should merge a pseudo user to existing userFarm when user is already member of the farm
[11:05:47]	
[11:05:47]	    expect(received).toBe(expected) // Object.is equality
[11:05:47]	
[11:05:47]	    Expected: 201
[11:05:47]	    Received: 400
[11:05:47]	
[11:05:47]	      1127 |           async (err, res) => {
[11:05:47]	      1128 |             expect(err).toEqual(null);
[11:05:47]	    > 1129 |             expect(res.status).toBe(201);
[11:05:47]	           |                                ^
[11:05:47]	      1130 |             const oldUserFarm = await userFarmModel
[11:05:47]	      1131 |               .query()
[11:05:47]	      1132 |               .findById([psedoUserFarm.user_id, psedoUserFarm.farm_id]);
[11:05:47]	
[11:05:47]	      at tests/userFarm.test.js:1129:32
[11:05:47]	      at Test.Object.<anonymous>.Request.callback (node_modules/superagent/lib/node/index.js:716:12)
[11:05:47]	      at node_modules/superagent/lib/node/index.js:916:18
[11:05:47]	      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/parsers/json.js:19:7)
[11:05:47]	
[11:05:47]	
[11:05:47]	Test Suites: 1 failed, 5 skipped, 29 passed, 30 of 35 total
[11:05:47]	Tests:       1 failed, 356 skipped, 779 passed, 1136 total
```

**Comment by Cali0707** [comment]
@smattingly I think this is the desired behaviour as described in JIRA, but the test is not testing it correctly - my understanding is that if a user already exists on a userFarm, then a pseudo user should not be allowed to be upgraded to the existing user

**Pull request merged**
