### PR TITLE
Send local timezone for server check

### PR DESCRIPTION
**Pull request by smattingly**
See discussion in Jira [LF-2634](https://lite-farm.atlassian.net/browse/LF-2634)

### CODE REVIEW

**Comment by smattingly** [comment]
Since this bug fix has been removed from what will be v3.2.4, moving this PR onto integration.

**Comment by Cali0707** [comment]
@smattingly is this PR meant for the collab branch?

**Comment by smattingly** [comment]
@Cali0707 No, that was the point of my previous comment. We removed this from the fix release because I am concerned about potential ripple effects-- I want us to live with it for a while on beta before it is released.

**Comment by smattingly** [comment]
Closing this due to change in requirements.

**Pull request closed without merging**
