### PR TITLE
New Crowdin translations webapp_locales

### PR DESCRIPTION
**Pull request by LiteFarm-eng**
New Crowdin pull request with translations of webapp_locales

### CODE REVIEW

**Review by kathyavini — APPROVED** [review]
@Duncan-Brain odd; I thought we did the upload action _after_ I had removed the translated language names from CrowdIn 🤔

Maybe not though. Should be safe to run now, though, yes?

**Comment by Duncan-Brain** [comment]
I think this was a bug or missed translation that someone came back to! Should be good

**Comment by Duncan-Brain** [comment]
But you can check the upload download time frame if you're worried: 
Screenshot 2024-09-11 at 1 58 35 PM

Looks good to me tho

**Review by kathyavini — APPROVED** [review]
@Duncan-Brain ran the upload action and fixed those strings for your current ticket. I think it's good to merge 🙏 

Edit: ACK hold on a sec I think I see a typo!

**Pull request merged**
