### PR TITLE
[ngrok required to test] LF-2722: Long press for sensor reading preview on map is not working for clustered sensors

### PR DESCRIPTION
**Pull request by fsayyid**
Ticket: [LF-2722](https://lite-farm.atlassian.net/browse/LF-2722)

To test:
- Upload sensors with the same latitude and longitude.
- Run ngrok and access the farm map on a mobile device.
- Click the clustered sensors to see the list of sensors in one location.
- Long press a sensor to see the preview

### CODE REVIEW

**Review by Cali0707 — COMMENTED** [review]
@fsayyid this is working, but it is very finicky to get the long press to work correctly. If I press for slightly the wrong amount of time, I get this behaviour:
IMG_B342A595BAF8-1

Up to you whether you think we should approve this now and open a bug ticket for that, or if you'd prefer to work on that now

**Comment by fsayyid** [comment]
@Cali0707 I'm pretty sure that was just because of the icon. I think now that I made the icon "un-selectable", it should solve this issue. But if it doesn't we can create a separate bug ticket for this.

**Review by Cali0707 — APPROVED** [review]
@fsayyid looks like that fixed it

**Review by seinnlee — APPROVED** [review]
Tested with dev tools and it looks good to me.

**Pull request merged**
