### PR TITLE
Lf 3983 create animal batch table and supporting table

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**
This adds the tables for animal_batch and animal_batch_sex_detail. It is a branch of #3083  and copies the structure of those tables.

Jira link:[ LF-3983](https://lite-farm.atlassian.net/browse/LF-3983)

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [x] Other (please explain): 
  - migrates up and down

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [x] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by antsgar** [comment]
@Duncan-Brain this one still needs the permissions, correct?

**Comment by Duncan-Brain** [comment]
@antsgar I assumed the same permssions to edit an animal applied to animal batches?

**Comment by antsgar** [comment]
@Duncan-Brain they should work in the same way, yeah, but since we're treating them as separate entities I think I'd prefer that we keep the permissions explicit too

**Comment by Duncan-Brain** [comment]
@antsgar Permissions are now added ..I can deal with the explicit approach ahah

**Review by antsgar — APPROVED** [review]

**Review by SayakaOno — APPROVED** [review]
Looks good to me!

**Pull request merged**
