### PR TITLE
Lf 4286 cherrypick address minor changes

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

TODO:

The choice was made to delay the implementation of https://lite-farm.atlassian.net/browse/LF-4246 .

This covers some other small migrations that were going to be handled as part of that.

- add constraints to disallow negative numbers
- handle existing negative numbers on soil_amendment_task
- ~~rename tables to the singular form instead of plural (most file changes are this)~~
- add uniqueness constraint on soil_amendment_task_product to prevent duplicate (product_id, task_id)
- add not null constraint on product table for column ‘type’
- repair created_by and and created_at on soil_amendment_task_product

Jira link:

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by kathyavini** [comment]
@Duncan-Brain so `checkPositive` IS failing on 0...

**Review by kathyavini — COMMENTED** [review]
So I think I did find the steps to reproduce the unique violation error. I believe the root cause is similar to the over-aggressive deletion I showed (both involve using the dropdown to select a duplicate product without using the remove).

Steps:
1. Create a task with products A and B
2. In complete, delete product B and change A to B in the dropdown
3. Add a new product and select A

I assigned the same purposes as well.

Database error:

```json
{
  "error": {
    "name": "UniqueViolationError",
    "nativeError": {
      "length": 343,
      "name": "error",
      "severity": "ERROR",
      "code": "23505",
      "detail": "Key (task_products_id, purpose_id)=(117, 2) already exists.",
      "schema": "public",
      "table": "soil_amendment_task_products_purpose_relationship",
      "constraint": "soil_amendment_task_products_purpose_relationship_pkey",
      "file": "nbtinsert.c",
      "line": "671",
      "routine": "_bt_check_unique"
    },
    "client": "postgres",
    "table": "soil_amendment_task_products_purpose_relationship",
    "columns": [
      "task_products_id",
      "purpose_id"
    ],
    "constraint": "soil_amendment_task_products_purpose_relationship_pkey",
    "level": "info",
    "service": "user-service",
    "error": {
      "message": "insert into \"soil_amendment_task_products_purpose_relationship\" (\"purpose_id\", \"task_products_id\") values ($1, $2), ($3, $4), ($5, $6) returning \"task_products_id\", \"purpose_id\" - duplicate key value violates unique constraint \"soil_amendment_task_products_purpose_relationship_pkey\""
    }
  }
}
```

**Comment by Duncan-Brain** [comment]
I like faulty un-retire as opposed to over-agressive delete haha. I don't think anything gets deleted just overwritten.

@kathyavini I reverted the controller and will check that case.

**Review by kathyavini — APPROVED** [review]
Works very well, thank you 🙏 

And we'll see what comes out of bug bash... might have to use some of this logic (or at the very least it was useful to have looked into) as we run into duplicate product stuff. And of course for the future if needed with a true PATCH.

**Review by SayakaOno — APPROVED** [review]

**Pull request merged**
