### PR TITLE
LF-4221 (0): Translations for application method

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

Jira link: https://lite-farm.atlassian.net/browse/LF-4221

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by Duncan-Brain — APPROVED** [review]

**Comment by kathyavini** [comment]
Wait I thought we were moving towards only pushing the `en` file 😅??! @Duncan-Brain you're approving the opposite of what you said in tech daily

**Comment by Duncan-Brain** [comment]
@kathyavini It shouldnt matter. What I remember saying was: 

- there is some benefit to the developer to see MISSING, and it also at the same time annoying to unapprove MISSING, and see the diffs. 

With upload translations and auto-approve off this should be fine. We do not need to add MISSING., but I think it is okay to.

**Comment by kathyavini** [comment]
@Duncan-Brain yeah I agree with `upload_transations: false` off it doesn't matter; I just was hoping to stick to some consistency in our new process

**Comment by Duncan-Brain** [comment]
@kathyavini Cool, yeah hopefully we will have a good idea of the best process after this release!

**Pull request merged**
