### PR TITLE
LF-4351: Other purpose text is not saved

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

- Set ``OTHER_PURPOSE_ID` in useEffect.
- Remove `value` and `defaultValue` from the input to avoid the controlled/uncontrolled warning.
- Remove out-dated comment.

Jira link: https://lite-farm.atlassian.net/browse/LF-4351

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by kathyavini — APPROVED** [review]
I have never been able to get this behaviour happening locally to test, but the code change makes sense!

**Comment by SayakaOno** [comment]
Thank you @kathyavini ! The reproduction rate is 100% for me so far; it needs to be started without purposes in the Redux store (testing right after logging in is the easiest), and if you run it with a throttle, you might be able to see it too. (But no need to re-test :) )

**Review by Duncan-Brain — APPROVED** [review]
Fixes it for me!

**Comment by kathyavini** [comment]
@SayakaOno ah okay thank you! With throttling I was able to see the query still `pending` with the page loaded and the value missing!! I was thinking of this in the wrong way entirely then because I had assumed the `undefined` was just the form's initial load behaviour and not the actual value being missing (or if I had known about the missing value, I had forgotten by today 😂)

**Pull request merged**
