### PR TITLE
LF-4451 Update node version to match nvmrc for backend

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

@kathyavini  -- wondering if you are down to test this fix of updating node on actions! It would need to be done at some point anyways.

I do not believe I am seeing this bug locally when I run tests -- its hard to tell because I am seeing the tests run into memory issues again due to the time it takes to complete of our tests. But in the ones that complete and fail I couldn't see the specific error.

Jira link: [LF-4451](https://lite-farm.atlassian.net/browse/LF-4451)

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-4451]: https://lite-farm.atlassian.net/browse/LF-4451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Not always sure if latest action updates will run on branch specific code. But it looks like it passes and worked:

Screenshot 2024-09-18 at 9 22 09 AM

**Review by kathyavini — APPROVED** [review]
Sounds good to me! Let's test i!

**Comment by kathyavini** [comment]
@Duncan-Brain any idea how to get the other branch to run its test with the updated Node? I thought re-running the API tests would be enough but it's still on Node 16.

Screenshot 2024-09-18 at 1 37 07 PM

Maybe PR has to be closed and re-opened?

**Comment by Duncan-Brain** [comment]
@kathyavini true ! Back to the drawing board, thanks for trying it with me!

**Pull request merged**
