### PR TITLE
Switched tasks to keep dates in UTC

### PR DESCRIPTION
**Pull request by Cali0707**
This PR fixes the bug described here by switching all the task dates to be handled in UTC

To test:
1. Create a task
2. Update the task's due date to be today
3. This should work

### CODE REVIEW

**Review by jagDhillon077 — CHANGES_REQUESTED** [review]
Screen Shot 2022-07-21 at 3 12 37 PM
In this view if I change the due date to today's date or any other date it works as intended.

When I click on the task card and check it's due date the value is pre populated correctly.

Screen Shot 2022-07-21 at 3 17 39 PM

However if I try to change the due date in the task details view it always changes the date to one behind the selected date. ex: setting the due date to today will give the task a due date of yesterday. But it looks like it is only a frontend updating issue because If I click off the task and re click the details tab it populates correctly.
Available on Slack if you require any further clarifications

**Comment by Cali0707** [comment]
@jagDhillon077 good catch - looks like I hadn't updated it everywhere!

**Review by jagDhillon077 — APPROVED** [review]
LGTM - works perfectly now

**Review by smattingly — COMMENTED** [review]
See discussion in Jira [LF-2634](https://lite-farm.atlassian.net/browse/LF-2634)

**Comment by smattingly** [comment]
I don't expect any further work on this branch/PR, but we can reopen if needed.

**Pull request closed without merging**
