### PR TITLE
LF-3033 Patch production (main) with Google SSO changes

### PR DESCRIPTION
**Pull request by kathyavini**
**Description**

These are the Google SSO code changes from [PR #2455](https://github.com/LiteFarmOrg/LiteFarm/pull/2455) & [PR #2461](https://github.com/LiteFarmOrg/LiteFarm/pull/2461) cherry-picked and applied to the main branch in order to patch production.

A fresh `pnpm install --frozen-lockfile` with the main branch lockfile was used to generate the `webapp/package.json` and `webapp/pnpm-lock.yaml` of this PR. The same version of @react-oauth/google currently on integration/beta (@^0.7.0) was installed.

**Some notes on testing this branch locally**
- You will need to rebuild/migrate the database to the same state as prod/main to test the invites, or you will just get a database error when trying to create an account
- You will need to `npm ci` on the prod/main `package-lock.json` and re-migrate the `test_farm` database if you would like to run `jwt.test.js`

Jira link: https://lite-farm.atlassian.net/browse/LF-3033

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Passes test case
- [x] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [x] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by SayakaOno — APPROVED** [review]
It works for me!

**Comment by SayakaOno** [comment]
@kcussen should we bump the version?

**Review by Duncan-Brain — APPROVED** [review]
Lets try it out!

**Review by kcussen — APPROVED** [review]
LGTM!

**Comment by SayakaOno** [comment]
I referred [this commit](https://github.com/LiteFarmOrg/LiteFarm/commit/f27c1c3c4cd5ff60c17cad05c8a78b4e25281964) and bumped version numbers.

**Pull request merged**
