### PR TITLE
fix: retire ESCI sensor bug

### PR DESCRIPTION
**Pull request by fsayyid**
To test:
- Retire an esci sensor

### CODE REVIEW

**Review by AbdusShaikh — APPROVED** [review]
Works and code makes sense

**Review by Cali0707 — CHANGES_REQUESTED** [review]
@fsayyid the sensor retired successfully when I did this, but I had to refresh the map for it to go away

**Comment by fsayyid** [comment]
@Cali0707 I think @AbdusShaikh 's PR handles this issue [#2195](https://github.com/LiteFarmOrg/LiteFarm/pull/2195)

**Review by Cali0707 — APPROVED** [review]
Looks good

**Pull request merged**
