### PR TITLE
Automatically add JIRA ticket number to commit messages

### PR DESCRIPTION
**Pull request by navDhammu**
**Description**

This is a little feature I worked on for myself to automate the process of adding a JIRA ticket number to commit messages. I was getting a bit tired of having to remember to add it everytime I make a commit, so I experimented and came up with this solution. I just wanted to share it here in case others may benefit from it as well and potentially merge it in the repository. 

**What it does**
Automatically adds the JIRA ticket number to the commit message on each commit.

**How it works**
Git natively provides several hooks that allow you to do something on certain actions. Like the pre-commit hook allows you to run some code before committing, there are several others documented [here](https://git-scm.com/docs/githooks). 

For this case I used the prepare-commit-msg hook that allows you to modify commit messages before a commit. Since LiteFarm is using husky, I set up the hook under .husky as mentioned in their docs. I used node.js because that's what I'm most familiar with but it can be done in other ways like using bash scripting.  

What the script does is checks for the presence of a Jira ticket number in the branch name, and if it exists, reads the commit message and adds it to the front.

**Tests**
I added tests for automatically testing a few different scenarios and edge cases. Initially I set it up without mocking - by creating a test branch, making test commits on that branch, then checking for the presence of ticket number in the commit message. But I found that it was slow (500ms - 1s) and prone to inconsistencies, so I ended up refactoring to use mocks. 

_Note:_ 
- The tests use built-in node test runner so nothing is required to be installed, but node.js version 18 or higher is needed. For best results, use version 20, as it has the stable release for the test runner.
- To run the tests, use command `node --test /pathToTestFile`

**How to test manually:**
1. Checkout this branch locally and run npm install or npm run prepare
2. Change the branch name so that a fake jira ticket number is appended to it. Like LF-XXXX branch-name.
3. Make a test commit without adding a ticket number to it.
4. Hopefully you should have the JIra ticket number automatically added to the message.

**Type of change**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Hey ! Pretty neat! It works for me if I use the message flag on `git commit -m "message"`. But not when I make a longer commit message with editor using plain old `git commit`.

Is that expected?

**Comment by navDhammu** [comment]
@Duncan-Brain Thank you for having a look at this

Do you mean when making a commit inside an editor like vim? I don't usually use that so didn't take that into consideration. But I think what may be happening is that it's matching the ticket number inside the comments that are autogenerated in the editor.

```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch LF-3443-test-brach
# Changes to be committed:
```

**Comment by Duncan-Brain** [comment]
@navDhammu 

Yes plain old `git commit` that may default to vim. Our previous tech lead Ivan mentioned we should be preferring this method. I still use `-m` short message flag for most commits. But longer commit messages I will use the editor.

It is handy that the branch number is previewed in the vim commit comments. But I still need to manually enter it for it to be added to my commit message. I think what I was expecting is that a message using base command`git commit` also pre-populates the ticket number.

**Comment by navDhammu** [comment]
@Duncan-Brain I made some changes to work with the editor. Please let me know if it's working for you now.

- The `prepare-commit-hook` was running before the editor is opened so I changed it to use `commit-msg` hook which runs after.
- Added some filtering to filter out lines starting with '#' so the regex doesn't match the ticket number inside the comments

**Review by kathyavini — APPROVED** [review]
I think this is great! I learned some stuff reading this (didn't know there was a Node test runner!) and the test cases cover all the variants I can think of.

**Review by Duncan-Brain — CHANGES_REQUESTED** [review]
So it must be matching something else I am getting the already exists error on the message.

git commit > i(insert) > type in message above comments>ctrl^c>:w(write)>:q (exit vim)

Screenshot 2024-08-08 at 4 41 30 PM

I also haven't tried setting my default editor to anything else like nano or somethig.

Flag still works:

**Comment by navDhammu** [comment]
@Duncan-Brain Thats weird, its working for me when I do the exact same steps you described... did you forget to pull latest changes?

**Review by SayakaOno — APPROVED** [review]

**Review by Duncan-Brain — APPROVED** [review]
Your right I must not have had recent changes -- i remember both rebasing, because it was rebased and deleting because I suck at rebasing others branches.

But it works now!

**Pull request merged**
