### PR TITLE
LF-4341: The text overlaps the borders of the save button on mobile device

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

- Truncate text in InFormButtons
   - Remove padding
   - Set display to `inline-block` 
- Update InFormButtons to take `className`
- Add max-width to the buttons in `InFormButtons`. Without max-width, the container width extends to accommodate the buttons' width.

I can't do better than this now 😣😣😣😣😣🤮 If you have any suggestions, please let me know!

Jira link: https://lite-farm.atlassian.net/browse/LF-4341

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by Duncan-Brain — APPROVED** [review]
I am fine with this fix haha 

But it is a design flaw for sure! 

I would also be happy with telling Loic we changed his design to one of these when he gets back:
- removing "Editing..." from all views
- moving "Editing..." to other text "Any changes will affect ... " for all views to become "Editing... any changes will affect ... "
- Changing "Save Product" to "Save"

**Review by kathyavini — COMMENTED** [review]
When I looked at the ticket I actually thought the plan was just to make a super tall button 😂  Compared to that I think the truncating solution looks great!!

As @Duncan-Brain said it's a design issue now and we're going to have to make some design decisions ourselves, but I'm concerned about how neither cancel nor save is visible as a full word anymore in other languages:

Screenshot 2024-07-23 at 12 20 48 PM

Screenshot 2024-07-23 at 12 20 00 PM

Screenshot 2024-07-23 at 12 19 15 PM

I think I would vote to flex wrap or even toss "Editing..." at `xs-breakpoint` in favour of letting the functional buttons be clear:

(This is ugly! But clear)
Screenshot 2024-07-23 at 12 48 49 PM

(I think my preference as editing was always meant to be helpful text)
Screenshot 2024-07-23 at 12 49 40 PM

What do you think? Should we UX/UI channel it? It's really a design call I think...

Edit: Oh I didn't notice Duncan's edits. So my vote is closest to bullet point one but I think remove it just for mobile; no need to mess with the Desktop view which is ideal. "Product" part of save is definitely necessary as there are two forms on this page! 🥲

**Comment by Duncan-Brain** [comment]
Also good with Joyces suggestion -- I just  thought maybe deleting from all views would be easier, less code, consistent but just mobile view is also cool with me!

And the other form button is "continue" vs "save" so I thought it might be distinguishable enough -- but yeah not top 
 option.

**Comment by SayakaOno** [comment]
Thank you both! I'll go with the easiest option: hide "Editing..." for mobile.

**Review by Duncan-Brain — APPROVED** [review]

**Review by kathyavini — APPROVED** [review]
I think every few weeks I google how to truncate text on a flex container at the point that the parent would expand, and I still have no idea how to do it 😭 CSS can be so annoying sometimes!

At 150px "Save Product" still cuts off in Spanish and French, but this is definitely the best iteration given the design. Thank you!! 🙏

**Pull request merged**
