### PR TITLE
Fixed infinite loop

### PR DESCRIPTION
**Pull request by Cali0707**
Per https://lite-farm.atlassian.net/jira/software/c/projects/F21/boards/3?modal=detail&selectedIssue=F21-666 

When you abandoned a crop management plan and then click on it's detail page, you would be caught in an infinite loop. This PR fixes the routing to remove the infinite loop

### CODE REVIEW

**Review by jagDhillon077 — CHANGES_REQUESTED** [review]
I am still getting an infinite loop after pressing "<" after abandoning a crop plan.

**Comment by jagDhillon077** [comment]
@Cali0707 This fixed the issue however it inadvertently removed the functionality where the "<" button is contextual. So if I accesses the crop management page via the farm map it should be returning me to the farm map however it returns me to the crop catalogue instead. See [The Jira Ticket I am reffering to](https://lite-farm.atlassian.net/browse/LF-2318)

**Review by jagDhillon077 — CHANGES_REQUESTED** [review]
See comment above

**Comment by jagDhillon077** [comment]
Hey @Cali0707. The back button still looks like it is not contextual. I tried to access a crop management plan via the farm map and immediately tried to go back and it returned me to the crop catalogue. Is it working on your end?

**Review by jagDhillon077 — CHANGES_REQUESTED** [review]
Hey @Cali0707. The back button still looks like it is not contextual. I tried to access a crop management plan via the farm map and immediately tried to go back and it returned me to the crop catalogue. Is it working on your end?

**Comment by Cali0707** [comment]
@jagDhillon077 this is working on my end, have you pulled the latest changes?

https://user-images.githubusercontent.com/65566908/171909077-ea45cbb9-4469-40b2-8cae-f45fdeab26a7.mov

**Comment by Cali0707** [comment]
@jagDhillon077 it should be working now for completed and abandoned plans too!

**Review by jagDhillon077 — APPROVED** [review]
LGTM, the infinite loop problem has been fixed. Thanks @Cali0707

**Review by smattingly — APPROVED** [review]

**Pull request merged**
