### PR TITLE
[LF-2139] Link to tutorials in the menu

### PR DESCRIPTION
**Pull request by hernandcb**

### CODE REVIEW

**Comment by hernandcb** [comment]
Where do you think is better to store the urls to the different youtube playlists?
I don't like the idea of having those urls in the code or the i18n files, perhaps in a config file?

**Comment by JimmyRowland** [comment]
I think it's fine to store URLs in that function

**Comment by hernandcb** [comment]
Thank you, I did it as you suggested.

**Review by smattingly — APPROVED** [review]
:+1:

**Pull request merged**
