### PR TITLE
3.6.7 Backport (Main -> Integration)

### PR DESCRIPTION
**Pull request by kathyavini**
**Description**

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Jira link: https://lite-farm.atlassian.net/projects/LF/versions/10026/tab/release-report-all-issues

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by kathyavini** [comment]
Made a ticket for the failing API tests [here](https://lite-farm.atlassian.net/browse/LF-4451)

**Review by Duncan-Brain — APPROVED** [review]

**Comment by Duncan-Brain** [comment]
I think we will need to merge integration to see the new github action into here to see it work: 
Screenshot 2024-09-18 at 4 38 41 PM

**Comment by kathyavini** [comment]
> I think we will need to merge integration

Wait what, no this PR branch is main! Definitely CANNOT merge integration into main!!! Let me try resetting the base branch to see if it updates, and otherwise I'll reopen the PR. Integration itself is already updated so I don't know why the API tests are running on what seems like... cached version of integration or something?

**Comment by Duncan-Brain** [comment]
@kathyavini good point about it being main 😂  -- hopefully you are right tha tit is just that the action server is cached that might make sense!

Otherwise could probably merge that one commit into main (even though its not our process) or wait to backport until after translations if we put that one commit in the `patch/translations`.

**Pull request closed without merging**
