### PR TITLE
LF-2875_refactor_architecture

### PR DESCRIPTION
**Pull request by wasswarichard**
Fix incorrect irrigation_type_id for an irrigation_task created.

### CODE REVIEW

**Comment by anant00729** [comment]
@wasswarichard tested the PR. based on the farm_id. I can see the other irrigation type name in one farm 
and if I switch to another farm the custom irrigation type is not present. 

 this looks good to me.

Add Screenshots of the tests:

Screen Shot 2022-12-23 at 3 30 35 PM


Screen Shot 2022-12-23 at 3 31 04 PM

**Review by anant00729 — APPROVED** [review]

**Comment by wasswarichard** [comment]
@Duncan-Brain for Issue that's a known behavior, we have had several conversions including @kcussen 
Issue 2 has been resolved.

**Comment by kcussen** [comment]
I believe some of @wasswarichard recent commits around default values on the irrigation_task are related to this conversation on LF-2804:
[
](https://lite-farm.atlassian.net/browse/LF-2804?focusedCommentId=14497)

@wasswarichard can you please add descriptions to your PRs and comments to guide your approvers as you make commits - especially when those commits are to address issues found in verification / validation.

**Review by Duncan-Brain — DISMISSED** [review]
irrigation_type_id seems to be correct to me. The discussed issue about Custom types duplicates is being handled on LF-2804.

**Review by Duncan-Brain — APPROVED** [review]
Approval now that tests are passing. Please make a new branch and new Jira ticket describing the custom duplicates issue.

**Pull request merged**
