### PR TITLE
LF-3649 Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

### PR DESCRIPTION
**Pull request by kathyavini**
**Description**

Several requests made in succession to some of the routes of

- https://github.com/LiteFarmOrg/LiteFarm/pull/2849

(done in Postman; for the most part the frontend prevents these particular requests) leads to the the beta API hanging with knex timeout error. It was belatedly observed that some logical paths in the controllers were lacking either a `trx.commit()` or `trx.rollback()`.

Noted, but not undertaken in this PR because it would be a significant refactor, is that the other Objection.js transaction sytnax described [in this ticket](https://lite-farm.atlassian.net/browse/LF-355) automatically closes transactions. For me that is arguably preferable (safer at the cost of being less explicit) but this is subjective and team member opinions differ.

Syntax or transaction handling is not changed in this PR (edit: other than adding it to the query methods; didn't realize it was needed, thank you @Duncan-Brain for pointing that out).

Jira link: https://lite-farm.atlassian.net/browse/LF-3649

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [x] Other (please explain)

Tested in Postman with the route (POST to `/expense_type/`) and request body from the Jira ticket.

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by Duncan-Brain — COMMENTED** [review]
Should we pass trx to isDeleted and existsInFarm too?

**Comment by kathyavini** [comment]
@Duncan-Brain interestingly I had that backwards -- I thought with `transaction.start()` passing trx was not necessary and with the callback it was... and because I didn't want to pass to the methods I stayed with the explicit handling. But if that's backwards I'm moving to callback 😆 

I'm starting to hate the Objection.js transaction docs with a passion, for showing 3 different creation syntaxes and 2 different usage syntaxes all mixed up.

**Review by SayakaOno — APPROVED** [review]
Looks good to me!

**Comment by Duncan-Brain** [comment]
Works well for me! 

I think that restart policy addition to our docker file must be working well because it does crash my local completely so I have to restart.

**Review by Duncan-Brain — APPROVED** [review]

**Pull request merged**
