### PR TITLE
Fix validation condition to show errors for selecting invalid CSV file

### PR DESCRIPTION
**Pull request by anant00729**
To Test.

1. select an invalid file format and check the validation errors.

https://lite-farm.atlassian.net/browse/LF-2616

### CODE REVIEW

**Review by Cali0707 — CHANGES_REQUESTED** [review]
There is still a need to check if the file has any rows on the backend @anant00729 

If you want, I can push the necessary changes for that onto this branch. I do think that we should have that in place before we merge this however

**Comment by anant00729** [comment]
Yes, you can add that validation on the backend.

**Comment by Cali0707** [comment]
@anant00729 I've updated the backend code, but you will need to handle the new `error_type` on the frontend before this is ready to go. The new `error_type` is `empty_file`

**Comment by anant00729** [comment]
I am doing all the validation that includes an empty file on the frontend before making the API call. I don't think there will be a situation where I need to handle that,

**Comment by anant00729** [comment]
I have tested the scenario of empty file upload for the backend. It works for me. @smattingly Please review.

**Review by Cali0707 — APPROVED** [review]
Looks good

**Review by smattingly — APPROVED** [review]

**Pull request merged**
