### PR TITLE
LF-3185 Update deployment script to only pull integration rather than the whole repo

### PR DESCRIPTION
**Pull request by kathyavini**
**Description**

The code change here is very slight (`git pull origin integration` in place of `git pull`) but this PR also relocates the beta deployment script from `deploy.sh` on the droplet (outside of our repository code) into our repository.

The `set -eu` addition is part of [LF-3067](https://lite-farm.atlassian.net/browse/LF-3067); please see that ticket for details.

Jira link: https://lite-farm.atlassian.net/browse/LF-3185

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

This is another ticket that can only be tested by observing the beta deployment GitHub Actions workflow.

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-3067]: https://lite-farm.atlassian.net/browse/LF-3067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by Duncan-Brain — APPROVED** [review]
Looks good to me.. only one way to test!

**Comment by kathyavini** [comment]
> Let's move the content of the `script:` key to a `.sh` file, easier to edit and lint

Sounds good. I don't think we have any linting set up yet in the root directory of the project (or probably for shell scripts anywhere...) should that be its own ticket?

**Review by iperdomo — APPROVED** [review]

**Review by Duncan-Brain — APPROVED** [review]
Looks good to me! But how do you feel about renaming the workflow beta-deploy too?

**Comment by kathyavini** [comment]
@Duncan-Brain yes, you're right, it should be. For now I don't mind so much (it at least keeps the deployment record in one place), but I imagine it will get renamed the moment we add prod CI/CD.

**Pull request merged**
