### PR TITLE
LF-3028: Mismatch between visualized high and low temps and reported high and low temps

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

In the temperature chart, the current lowest and highest observed temperature are shown whereas they should be the forecasted high and low temperature for the day.
- call the [daily forecast API](https://openweathermap.org/forecast16) to get the forecasted high and low temperature for the day
- update useEffect dependency to show high/low temperature in the sensor chart

Jira link:
- https://lite-farm.atlassian.net/browse/LF-3028
- https://lite-farm.atlassian.net/browse/LF-3256

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [x] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Works for me but just wondering if we can deprecate the currentDayWeather response totally by using the name field in the new api call?

**Comment by SayakaOno** [comment]
Thank you @Duncan-Brain, I removed the API call.

**Review by Duncan-Brain — DISMISSED** [review]
@SayakaOno thanks looks great.

Only thing I wonder if text in the UI should be explicit about "Today forecasted ambient .."

**Comment by SayakaOno** [comment]
@Duncan-Brain Thank you!
I'm not sure if the whole translations need to replaced with "MISSING"...

**Review by kathyavini — APPROVED** [review]
Oh no, I think your translations will end up getting changed again with the new format anyway!

But this looks great and the fixed `useEffect` solves so many issues, thank you! Big approval!! 👍

**Review by Duncan-Brain — APPROVED** [review]
@SayakaOno 

I would normally replace the whole string with MISSING. But I think they will probably find it this time.

**Pull request merged**
