### PR TITLE
Fixed page failing by providing default value

### PR DESCRIPTION
**Pull request by Cali0707**
The page was crashing because `prev_planting_management_plan` was undefined and one of its keys was accessed. A more detailed discussion of the issues can be found [here](https://lite-farm.atlassian.net/browse/LF-2287). This was fixed by providing a default value for `prev_planting_management_plan`

### CODE REVIEW

**Comment by seinnlee** [comment]
How do I recreate this bug on local? When I created an unassigned transplant task,`prev_planting_management_plan_id` exists. Is there a specific flow that I have to follow to trigger this bug?

**Comment by smattingly** [comment]
@seinnlee From your comment, I'm guessing that you are/will peer review this one? If so, please assign yourself as Reviewer. That way we'll know which PRs are covered. Thanks!

**Comment by Cali0707** [comment]
> How do I recreate this bug on local? When I created an unassigned transplant task,`prev_planting_management_plan_id` exists. Is there a specific flow that I have to follow to trigger this bug?

This issue came up on some older farms that did not migrate properly. To recreate locally, you can go into "pg-litefarm" and execute:
```sql
UPDATE transplant_task SET prev_planting_management_plan_id = NULL WHERE task_id = ?;
```
All you have to do is substitute a task id corresponding to a transplant task in for the `?`. Hope that helps!

**Review by seinnlee — APPROVED** [review]
@Cali0707 Thanks! I was able to manually update the db and test it. It looks good to me. Btw, do we want to update `testEnvironment.js` file in this PR? I thought @smattingly was going to make a separate PR for this

**Comment by smattingly** [comment]
Good question @seinnlee. I thought the `testEnvironment` change was on one of the PRs that had merged by now, but I apparently lost track of it. It's not on integration branch, so we'll let it flow here. 
(Even if it were on integration branch, there would be no harm with repeating it here.)

**Pull request merged**
