### PR TITLE
LF-4153 Create animal creation wizard progress bar

### PR DESCRIPTION
**Pull request by kathyavini**
**Description**

This creates a `<StepperProgressBar />` (a styled [MUI React Stepper](https://mui.com/material-ui/react-stepper/)) to be used with multi-step forms such as the upcoming add animals. This is a good component for investigating with the [Storybook controls](http://localhost:6006/?path=/docs/components-stepperprogressbar--docs) to see the different states (step through `activeStep`).

[Figma specification](https://www.figma.com/file/eMffC0h3JPlWtzNttxJpil/Litefarm-Updated?mode=dev)

There was an element of the Figma specification I could not implement. The mobileLayout (`alternativeLabel`) specification of the MUI stepper centres all elements within their flex container:

Screenshot 2024-03-22 at 2 54 40 PM

You can write manual logic to left + right justify the first and last element labels, but he other components of the stepper (connecting line & node spacing) are not set up to handle such an adjust:

Screenshot 2024-03-22 at 2 55 20 PM

_This is an issue that is probably solvable, but I suspect might not be worth the development time._ Unless anyone knows of a quick solution, I will probably ask Loïc when he's back on Monday if the left and right justification can be dropped from scope in favour of using the MUI default.

Jira link: https://lite-farm.atlassian.net/browse/LF-4153

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [x] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by antsgar — APPROVED** [review]
Looks so clean, love it! ❤️ I didn't understand the difference between the spec and the actual mobile version in terms of layout, looks the same to me?

**Comment by kathyavini** [comment]
Thanks @antsgar!

In the spec, the left and right labels are aligned to the edges of their respective containers, and the steps fill the whole container space. To me it looks way better in spec (it's a better use of space) but I would say it's almost impossible to achieve based on the MUI base, which I think has divided the whole space evenly by number of steps and then centre-aligned the content for each step.

Spec:

Screenshot 2024-03-25 at 11 15 41 AM


Implementation:

Screenshot 2024-03-25 at 11 12 48 AM

I'm a bit encouraged that difference didn't jump out to you, though! Maybe it only feels glaring because I've looked at it for a while 😄

**Review by SayakaOno — COMMENTED** [review]
Looks great!!!
I'm being picky, but in the desktop version, the lines seem a bit low compared to the other elements. (it looks perfect if they are raised about 3px) Is it because the icons are smaller than the MUI's example? It would be great if there's a way to address it...

**Comment by kathyavini** [comment]
Oh yes, quite true @SayakaOno, thanks! That's pretty annoying now that I see it 😁

**Review by SayakaOno — APPROVED** [review]
❤️

**Comment by antsgar** [comment]
@kathyavini ahhh I see now! It doesn't seem like that big a deal tbh 🙂

**Review by antsgar — APPROVED** [review]

**Pull request merged**
