### PR TITLE
Used Pill component in Abandon Task

### PR DESCRIPTION
**Pull request by gursimran-singh**
**Description**

In the AbandonTask component, the pill is coded without using the Pill component. This component should be reused in date options to avoid un-necessary coding and css file.

Jira link: https://lite-farm.atlassian.net/browse/LF-2997

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Try to abandon a task. The options should be having date coded in Pill component.

- [x] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by Duncan-Brain — APPROVED** [review]
Looks great thanks @gursimran-singh !

**Review by SayakaOno — COMMENTED** [review]
Nice cleanup! 

@Duncan-Brain do you remember we have two `Pill` components now? (The new one was created in this [PR](https://github.com/LiteFarmOrg/LiteFarm/pull/2578))
I want them to be combined or one of them to be removed. Would it be better to create a ticket...?

**Comment by Duncan-Brain** [comment]
@SayakaOno I definitely forgot! If there is one that should be used over the other here it might be good to switch it if you know which is best.

But yes definitely a new ticket to deprecate one.

**Comment by SayakaOno** [comment]
@Duncan-Brain I will create a ticket, thank you!
I think we should keep the old one. Some of the differences are that the new one takes `spaceBefore` and does not take additional styles, and it is less reusable.
I will request a change to Gursimran. I think we can discuss how we should deprecate one later!

@gursimran-singh could you switch the Pill component to the one you updated before? (`/packages/webapp/src/components/Filter/Pill/index.jsx`) I guess you will need to adjust the space 🙏

**Comment by gursimran-singh** [comment]
I have updated the code to use old pill component and also made changes in the pill component to use styles passed as a prop.

**Review by SayakaOno — APPROVED** [review]
Looks good, thank you!

**Review by Duncan-Brain — APPROVED** [review]

**Pull request merged**
