### PR TITLE
LF-4222: Fix sticky top bar

### PR DESCRIPTION
**Pull request by Joaquin-M2**
**Description**

The top bar of the application didn't stay at the top of the screen after scrolling.

Jira link: https://lite-farm.atlassian.net/browse/LF-4222

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [x] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
@Joaquin-M2 everything looks good to me.

I just have a questions for @kathyavini wondering if the side menu behaviour mentioned here is documented anywhere to test that this solution also works for that? https://github.com/LiteFarmOrg/LiteFarm/commit/b7dfd5eb0f1dd0d692448a873cc433749bab5968

**Review by Duncan-Brain — APPROVED** [review]

**Comment by kathyavini** [comment]
@Duncan-Brain do you mean like this: [LF-4055](https://lite-farm.atlassian.net/browse/LF-4055). That's a menu collapse button bug (actually it's still present on main/production) that was fixed by the commit you linked above.

**Review by kathyavini — APPROVED** [review]
Thank you so much!! I didn't know about this property at all; that's extremely useful.

**Comment by Joaquin-M2** [comment]
> Thank you so much!! I didn't know about this property at all; that's extremely useful.

The difference between overflow `hidden` and `clip` can be subtle, but it becomes more evident in use cases like this one in which a child was using a sticky position. [This article](https://medium.com/@ehsaneona/overcoming-position-sticky-issues-solving-overflow-hidden-problems-with-overflow-clip-e8e79a7b0c34) explains it quite well.

At first I wasn't sure about the fix, so don't think I'm some kind of css expert. My only useful skill is googling 😆

**Pull request merged**
