### PR TITLE
LF-3671 Add debugging to npm test script and vs code debug configurations to repository

### PR DESCRIPTION
**Pull request by kathyavini**
**Description**

Another developer experience PR, my favourite 😁 

This adds the ability to attach a debugger when running `npm test` (a run script that can safely be modified as it is only used locally).

Following @Duncan-Brain's excellent suggestion I have added `.vscode/launch.json` to the repo as launch configurations for the repo can and should be shared among developers for a consistent debugging experience. Configurations are included for the API (local or Dockerized), the `export_server` as configured by `docker compose up`, and the tests (to use with current `package.json` addition).

Please use by running `npm test` and then attaching using the "Debug Jest Tests" configuration from VS Code Run and debug:

Screenshot 2023-09-28 at 10 26 44 AM

If you don't attach the debugger the test script(s) will behave as normal.

Jira link: https://lite-farm.atlassian.net/browse/LF-3671

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [x] Other (please explain)

I use these configurations locally.

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by SayakaOno** [comment]
Thank you so much! I have tried to write `launch.json` before but couldn't get it to work, so I am happy now! 😄 
This works great if you open the `api` folder on VS code, but I open the root folder, so I want to have the same `.vscode/launch.json` in the root directory (if I added it, it would not be ignored). If we keep `.vscode` in `.gitignore`, will `api/.vscode` also be ignored?? (I guess that's what we saw this morning, but it doesn't seem to be ignored, so I figured I would double check!)

**Comment by kathyavini** [comment]
@SayakaOno wait, should I have been opening the root directory as my VS Code workspace all along??! 🤯 I'm so used to opening `webapp` and `api` separately (and then root as a third if I work with the docker-compose files 😆) ! If I'm the only one who does it that way let's put the `launch.json` into the root!

Otherwise (or if it ends up being too big a mental shift for me hehe) we can just replicate the file in two places to suit both workstyles. Yes the `.gitignore` setting will apply equally to both the root and nested folders and I think that's fine!

@Duncan-Brain which folder do you open as your workspace when you intend to debug the API?

**Comment by SayakaOno** [comment]
@kathyavini I thought you preferred to open webapp and api separately! 😆 In my previous company, there were separate repos for the backend and the frontend, so I didn't get used to the mono-repo quickly. It is much harder to find files in mono-repo...😂

**Review by SayakaOno — APPROVED** [review]

**Comment by Duncan-Brain** [comment]
@kathyavini ... I only open one workspace (root) since I honestly didn't consider other options.. haha.  but also it might drain less laptop resources haha. I do not customize anything... I am a default settings person 😬 . I like making tech but I do not explore it unless necessary haha.

The main reason root makes sense for me is that you could also add FE debugger stuff if thats useful?

I am not going to be helpful here, I would suggest asking someone else who might be using this config already. Mikael was very good at this stuff if you are willing to ask but this would be an awesome contrib channel ask/discussion.

**Comment by kathyavini** [comment]
@Duncan-Brain I was just curious what your personal preference was. The way this PR is written now it will work whether you consider root or `packages/api` your workspace so it doesn't really matter -- go ahead and test it!

I don't use launch configuration for frontend debugging as I prefer the Chrome devtools debugger UI to the VS Code integrated, and I just find it a more seamless experience overall when working on frontend. But yes the option is always open to add one in the future!

**Comment by antsgar** [comment]
@kathyavini I love this! Makes it so much easier to debug by just adding breakpoints instead of endless console.logs 😅 thank you for doing this, it's working well for me. I also just open up the root workspace instead of having two separate windows, I appreciate not having to switch back and forth, but to each their own 😂

**Comment by Duncan-Brain** [comment]
I think debugger is finicky for me for some reason. But I don't think its your configuration. I got the Local api working debugger, the jest tests didn't seem to work for me, and my docker hasn't been run in a while.

I see no reason to hold this up since two others have given their thumbs up!

**Review by Duncan-Brain — APPROVED** [review]

**Comment by kathyavini** [comment]
@Duncan-Brain for the jest debugger, you have to do it in this order: 1) set up your debugger statement, 2) run the test(s) with `npm run test <test_name>` and 3) then immediately attach the debugger in VS Code (before the test gets to your breakpoint -- you have to be a little quick, heh!)

Did you try it that way? If the API config is working the jest one should work too; they are basically the same.

**Comment by Duncan-Brain** [comment]
Haha .. no I did not try that quickdraw attach debugger technique! lol 

I will try to remember to try again next time I am debugging tests

**Pull request merged**
