### PR TITLE
LF-2642 crop plan based pop up for adding a location

### PR DESCRIPTION
**Pull request by seinnlee**
Ticket [LF-2642](https://lite-farm.atlassian.net/browse/LF-2642)

To Test:
1. Create a new farm without adding any locations on the map.
2. Create a new crop plan.
3. When entering select location page, there should be a popup.
4. Clicking "go back" will return the user to crop plan creation flow.
5. Clicking "create location" will redirect the user to the farm map with "+" tab expanded.

### CODE REVIEW

**Review by fsayyid — CHANGES_REQUESTED** [review]
After I create a location, the map drawer is still showing. I believe we should see the map after creating a location.

**Comment by seinnlee** [comment]
@fsayyid I fixed the issue you described!

**Review by fsayyid — APPROVED** [review]
This is looks good 👍

**Review by Cali0707 — APPROVED** [review]
Looks good to me, everything seems to be working as expected

**Pull request merged**
