### PR TITLE
Lf 2393 - Disable unit conversion on changing the value of unit selection dropdown component

### PR DESCRIPTION
**Pull request by anant00729**
To test:

1. start with the create a task flow.
2. in the forms, look for the unit conversion dropdown.
3. add a value to the input field.
4. make changes in the drop-down unit field.
5. check if the value in the input field remains the same after selecting a different unit field.

### CODE REVIEW

**Review by seinnlee — COMMENTED** [review]
@anant00729 Is there a reason why we're just commenting out instead of deleting this code?

**Comment by anant00729** [comment]
I am just keeping it for future use.

**Comment by seinnlee** [comment]
> I am just keeping it for future use.

Will we need it in the future? I thought we decided that this feature was counterintuitive @smattingly

**Comment by anant00729** [comment]
I have removed the commented code. Please check.

**Review by seinnlee — APPROVED** [review]
Functionally lgtm

**Review by smattingly — APPROVED** [review]
:+1:

**Pull request merged**
