### PR TITLE
LF-3129: Pressing enter in while searching for People at my farm takes me to Invite User flow

### PR DESCRIPTION
**Pull request by SayakaOno**
**Description**

preventDefault not to submit Profile form on hitting enter.

Jira link: https://lite-farm.atlassian.net/browse/LF-3129

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
@SayakaOno 

So I am not sure about how this works for accessibility and what is required for that. Is disabling Enter bad for ARIA. But the spacebar still works when the element is tabbed which is good.

It is weird that this whole element is wrapped in a form -- I don't think it is appropriate in this case and maybe deserves a refactor ticket so we do not have to disable enter.

**Review by Duncan-Brain — DISMISSED** [review]

**Comment by Pazzolo** [comment]
@SayakaOno  Another alternative is adding the ` e.preventDefault();` in the onSubmit method.  Something like this `onSubmit={e => { e.preventDefault(); }` Im not sure if that works in this case. In that way we dont disable the enter key

**Comment by SayakaOno** [comment]
@Duncan-Brain accessibility... good point!! This change was affecting forms in Account and Farm tabs (the user would not be able to send a form on hitting enter even if the focus is on the save button), so I added a check.
Since Account and Farm tabs have forms, I'm not sure about the best way to refactor this... but I agree that the people table is wrapped in a form.

@Pazzolo I tried it, but unfortunately it did not work :(

**Comment by Duncan-Brain** [comment]
@SayakaOno beyond refactoring ProfileLayout I don't have any good suggestions. I tried moving button outside of Form and changing type from 'submit' to 'button' but it didnt work. Maybe a hidden button and a submit button? Is this important for release? Could be a patch in my oppinion.

**Comment by SayakaOno** [comment]
@Duncan-Brain If it's in production already, I don't think we need to fix this now. But what's your concern about merging this PR?

**Review by Duncan-Brain — APPROVED** [review]
@SayakaOno 

Sorry, I read your comment and got confused about if you wanted to leave it. I did not see the changes.

This PR is good!

**Comment by SayakaOno** [comment]
@Duncan-Brain Sorry!! and thank you!!!

**Pull request merged**
