### PR TITLE
Docker with litefarm cli for development

### PR DESCRIPTION
**Pull request by mickenorlen**
## Updated 2023-04-20
 
# Docker compose
This PR includes a new setup for developing with `docker-compose`. As it doesn't modify any previous setup files, it can be merged in a beta state, and tested in parallel to previous setups. 

- The docker commit contains more information about the compose project structure. 
- How to actually work with the new setup is explained by the cli through it's verbose logging and documentation. 
- Use the provided cli commands to manage the project directly, or, if you want inspiration to experiment with your own compose commands, check the verbose logs for explanations of the commands that the cli runs internally.

# LiteFarm cli
As it isn't convenient for every developer to write complex compose commands, I created the LiteFarm command line interface `lfcli` to help working with the setup.

>  Instead of writing documentation about which commands to run,
>  why not create a script that actually runs those commands,
>  and generates its own documentation.

- The cli is completely self-contained in the cli directory and is not required for managing the docker setup.
- It is a helper that runs, logs and documents all the commands needed to manage the project. My hope is that this can help everyone get started and learn about how the new setup works as efficiently as possible, without the need for further documentation.
- The `web` and `api` commands provide a more convenient development server startup than the conventional 
`docker-compose up` by starting the services in an idle state and running the server commands explicitly.

 ## As light and simple as possible, yet scalable.
- The cli core is about 50 lines of code.
- All the documentation is generated in about 100 lines.
- Add 20 more lines to bring some color to the logs.
- The rest is command files, many of which are one-liners.
- To add a new command, just create a new script file in a commands directory.

## An interface between the command line and regular script files
- `lfcli` functions as an interface between the command line and regular script files.
- Available commands are defined by, and run their corresponding script files, found in the commands directory.
- Developers can experiment with their own commands by setting the `LITEFARM_USER_COMMANDS_DIR` variable in `cli/.env`

| Commands  | File structure |
| ------------- | ------------- |
| image | image |

## Command documentation, straight from the command file
Each individual command is documented at the beginning of the file between two docmarks `#####`. This documentation is then presented in a pretty format when calling `lfcli help my_command`.

| `lfcli help install`  | Install command file doc comment |
| ------------- | ------------- |
| image | install_help |

## The cli manual
The cli now also has its own manual following the same principle as the individual commands. Read the full manual with `lfcli man`

| Part 1  | Part 2 |
| ------------- | ------------- |
| image |image |

## Verbose logging
All commands now output verbose logging information about all the commands that are run internally. Enable verbose logging by setting `LITEFARM_VERBOSE=true` in `cli/.env` or by calling `lfcli` with the `-v` option.

image

## New faster setup of LiteFarm
This is how quickly LiteFarm can now be set up from scratch.

1. Install docker and start the docker service https://docs.docker.com/get-docker/
2. Fork LiteFarm (recommended) https://github.com/LiteFarmOrg/LiteFarm
   - Otherwise `git clone git@github.com:LiteFarmOrg/LiteFarm.git` 
3. Clone your fork: `git clone git@github.com:me/LiteFarm.git`

```BASH
cd LiteFarm
git remote add upstream git@github.com:LiteFarmOrg/LiteFarm.git
cp packages/api/.env.default packages/api/.env
cp packages/webapp/.env.default packages/webapp/.env
cp cli/.env.default cli/.env
# Update env variables and add missing api keys as needed

cli/lfcli man      # Check the invocation section in the cli manual
cli/lfcli help     # Show cli commands
cli/lfcli install  # Install containers and dependencies
cli/lfcli migrate  # Migrate db
cli/lfcli web      # Serve web in 1st terminal
cli/lfcli api      # Serve api in 2nd terminal when project is up
```

# Testing

1. Test the new setup process.
2. Read the new manual `lfcli man`.
3. Test to see that the commands are working as described. Check available commands with `lfcli help`. Check documentation for specific commands with eg: `lfcli help config`
3. Check also the individual commit descriptions for more information and reasoning, especially for the docker setup.

### CODE REVIEW

**Comment by Duncan-Brain** [comment]
Hi @mickenorlen 

Thank you so much for submitting this PR! I always appreciate any suggestions that might help make onboarding easier!

So this looks like a really cool project maybe I will separate my review into two topics:

1. Docker upgrades
 - We are definitely interested in improving our docker infrastructure and many of the changes you have made look very good!
 - It would be nice to review these changes separately from the CLI in separate PR's
 - Choosing Adminer as our main choice for development database browsing is interesting and I think you made some good points about possible share-ability when sharing SQL statements is not good enough. This might be something worth discussing at the group of devs level to see if there is any consensus about which (pgAdmin, Adminer, postico etc..) we should all be using. -- then incorporating into the local.dockerfile as an onboarding step after that consensus.

2. LiteFarm CLI
 - It would be nice to review these changes separately from the Docker upgrades in two separate PR's
 - This seems like a product decision and @kcussen might have some thoughts about introducing a LiteFarm CLI, or maybe even suggest a round table discussion or presentation about the potential benefits of custom CLI's to the group of developers on the team
 - This is a really cool project! But if I am being honest I am not confident that we need a LiteFarm CLI. My main concerns are:
     - Maintainability - Adding another language (bash) to the stack may make it difficult to keep functional if the main designer ever leaves
      - Docker is not super complicated and abstracting away some basic commands may impede learning of essential skills like docker and npm script commands

We are all a team and I think we are flexible if you want to host some sort of architecture proposal meeting where we vote on the decisions.

**Comment by mickenorlen** [comment]
@Duncan-Brain. Thank you for taking a look at this. Yeah, I understand your concerns. I would be happy to have a round table presentation of this whenever you have time.

My main goal when working with this has been to make it as simple, understandable and maintainable as possible - without losing performance/scalability. I'm also planning to push a patch with verbose logging so that you can see everything that is going on inside. I hope this will make the cli feel more understandable and help developers learn and experiment with their own commands.

- All the docker upgrades are in the first commit of this PR so they are easily separated if needed. 
- Everything related to the cli resides in the cli directory. So it is also a simple delete if it would lose its purpose in the future.
- Working with docker can actually be a bit more complex than it seems at first, depending on the setup and environment. At the very least it can become tedious to work with in development.
- It would be happy to add any additional tools, database managers etc as you like. It gives me joy to empower developers!

Let me know when you have time for that meeting!

**Comment by mickenorlen** [comment]
Added new features:
- A manual, `lfcli man`
- Documentation for all individual commands. `lfcli help command`
- Verbose logging option to show explanations of all the commands that are run internally. 

Updated PR description with the new changes

**Comment by iperdomo** [comment]
Dear @mickenorlen 

Thanks for your time and contribution to make LiteFarm better.
As discussed there is some effort to have a Dockerized development environment. Still work in progress, due to some performance issues with bind-mounts in mac OS, and other expected pre-commit hooks for linting staged code.

As of today, we have a a Docker/Docker Compose setup for _supporting services_ (postgres, redis, imaginary). The end goal is to have a setup with one command `docker compose up`, no `--build`, no extra `-f/--file` flags, etc. Optimized for development experience. The changes are tracked with this issue: https://lite-farm.atlassian.net/browse/LF-3335

The idea of having a `cli` for development is appealing, but we don't have the capacity to maintain all that shell/bash code.

For these reasons, we can't merge your changes as is. We'll still leave the branch as inspiration for some of the upcoming changes in issue LF-3335.

Thanks,

**Comment by mickenorlen** [comment]
I understand, good luck!

**Pull request closed without merging**
