### PR TITLE
Lf 4366 remove animal identifier placement

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

This deals with the remaining half of LF-4170. Removing animal_identifier placement.

*Remember if you run tests the enum tables will delete and the down function on migration won't work.

Jira link: [LF-4366](https://lite-farm.atlassian.net/browse/LF-4366).

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

[LF-4366]: https://lite-farm.atlassian.net/browse/LF-4366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by SayakaOno — DISMISSED** [review]
I'm surprised by how much code was needed to support just two inputs! But it feels great to clean it up.
Thank you!

**Comment by kathyavini** [comment]
@Duncan-Brain I was very slow to test it. Now I can't because migration directory corrupt. Could you merge integration for me? 😇

**Review by kathyavini — APPROVED** [review]
Thank you!!

Yes horrifying amount of code for one input. Maybe we can pin this to sprint-team or something as a warning to future selves 😂  (and product...)

Screenshot 2024-08-16 at 2 38 02 PM

**Comment by LiteFarm-eng** [comment]
Previously approved... merging

**Comment by Duncan-Brain** [comment]
previously approved with no changes -- merging

**Pull request merged**
