### PR TITLE
Remove pug dependabot

### PR DESCRIPTION
**Pull request by Duncan-Brain**
**Description**

Based on dependabot update, package is not a primary dependency. Email still works fine locally.

Jira link:[#3215 ]( https://github.com/LiteFarmOrg/LiteFarm/pull/3215 )

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [ ] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Review by kathyavini — APPROVED** [review]
Yes I guess that would have been the less lazy way to handle it!

Just curious: did you regenerate or manually modify the lockfile?

**Comment by Duncan-Brain** [comment]
@kathyavini  I used `npm uninstall` to handle it

**Comment by SayakaOno** [comment]
I tested it, and it worked, but I found that in the `email-template` [document](https://www.npmjs.com/package/email-templates), it's instructed to install `pug`. Do you still think it's safe?
(Here's the [PR](https://github.com/LiteFarmOrg/LiteFarm/pull/630) that installed `pug` as a reference)

Screenshot 2024-06-17 at 10 03 51 AM

**Comment by Duncan-Brain** [comment]
@SayakaOno  Ah yes I see now, it looks to me like a devDependency/utility then. 

Since it works without it, and isn't a dependency or used anywhere, I would have to believe it is safe. But yeah I do not know, weird one.

And I do not see any express config like so: https://expressjs.com/en/guide/using-template-engines.html

We could ask Jimmy though since he set it up?

**Comment by SayakaOno** [comment]
@Duncan-Brain I assume Jimmy just followed the instruction.

I would like to learn more about package installation in general.
It would be great if you could share your thoughts in tech daily tomorrow!

**Comment by kathyavini** [comment]
@SayakaOno thanks for tracking down the PR! That is what I wanted to see earlier ☺️ 

> Since it works without it, and isn't a dependency or used anywhere

pug IS used (check out the pug templates in `src/templates/emails`), or you can even try deleting the pug folders from the `node_modules` and it will crash the API like this:

Screenshot 2024-06-17 at 11 48 18 AM

But even without the top level install, they are installed as a dependency of `email-preview` which is a dependency of `email template`:

Screenshot 2024-06-17 at 11 50 55 AM

That makes me think the package instructions are just out of date, and the instructions to install pug indeed did come from the [initial commit](https://github.com/forwardemail/email-templates/commit/b39de8288a52a3ea2bc3f36f3380755cb868b1d4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) of that project, which is BEFORE `email-preview` was added as a dependency.

But who are we to doubt professional package maintainers 😂 I vote let's do as they instruct and leave it in, even if if their readme is inaccurate now.

**Comment by Duncan-Brain** [comment]
Yeah sorry bad communication on me again. Definitely a dependency for email-templates and is used by them. 

Still think its safe to uninstall as direct dependency of Litefarm since it is unused in our code, or add to devDependency, or keep. We can chat in tech daily but yah agree with everything there @kathyavini

**Review by SayakaOno — APPROVED** [review]

**Pull request merged**
