### PR TITLE
Lf 2659/multi language support for bulk sensor upload format on the front end

### PR DESCRIPTION
**Pull request by anant00729**
To test:

1. open the sensor upload modal. 
2. add the following attached files and check the validation is passing successfully.
3. Also, try editing the same files to see the validation error. 

[test-sensors-multilanguage.zip](https://github.com/LiteFarmOrg/LiteFarm/files/9194077/test-sensors-multilanguage.zip)

For more details, please check: 
https://lite-farm.atlassian.net/browse/LF-2659

### CODE REVIEW

**Review by Cali0707 — CHANGES_REQUESTED** [review]
@anant00729 when I try and download the template for FR, it is downloading nwith incorrect headers.
malformed_fr_translation

**Comment by anant00729** [comment]
If you open the same CSV file in vscode it will show you the correct set of sensor fields.

**Comment by anant00729** [comment]
@Cali0707 Please use this zip file for testing

[test-sensors-multilanguage.zip](https://github.com/LiteFarmOrg/LiteFarm/files/9194081/test-sensors-multilanguage.zip)

**Review by smattingly — APPROVED** [review]
As discussed, I think it makes sense to merge this now and live with the understanding that certain uploads will fail on the backend until a corresponding change is made.

**Pull request merged**
