### PR TITLE
Lf 3792 the sale will no longer be visible once the crop plan will be deleted completed or abandoned

### PR DESCRIPTION
**Pull request by navDhammu**
**Description**

This PR fixes the issue where revenue for a crop sale does not show the crop when the crop management plan for that crop is not active or planned. This can happen when the user deletes, abandons or completes a plan after generating a revenue.

Changes:
- Added a selector to select all management plans 
- Modified useSelector inside useCropSaleInputs to include management plans for crop(s) associated with that particular sale irrespective of their management plan status. 

Jira link: https://lite-farm.atlassian.net/browse/LF-3792

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**How Has This Been Tested?**

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Passes test case
- [x] UI components visually reviewed on desktop view
- [ ] UI components visually reviewed on mobile view
- [ ] Other (please explain)

**Checklist:**

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] The precommit and linting ran successfully
- [ ] I have added or updated language tags for text that's part of the UI
- [ ] I have added "MISSING" for all new language tags to languages I don't speak
- [ ] I have added [the GNU General Public License](https://lite-farm.atlassian.net/l/cp/BT0Dd7WW) to all new files

### CODE REVIEW

**Comment by antsgar** [comment]
@navDhammu thank you for working on a fix for this one too! The fix works great, the only issue I see is that since `useCropSaleInputs` is used both for viewing/editing an existing revenue but also creating one, this change will cause a crop that has no current plans to show up when creating a new revenue, which I think isn't intended behavior. I'm thinking we could probably send some parameter to the hook so that it knows whether to include crops from pre-existing sales or not. Alternatively, we could have `useSaleInputs` receive a parameter for the current sale (which would only be passed when editing/viewing) and extract the extra management plan needed from that specific sale.

**Comment by navDhammu** [comment]
@antsgar Thank you reviewing this. As far as I understand this doesn't allow crops that don't have a management plan to show up when creating a revenue. I tested this by marking a crop plan as complete and deleted and checking if it shows up when creating a revenue. 

`useCropSaleInputs` already accepts a sale parameter which is what I used to filter the management plans:

```
const managementPlans = useSelector((state) =>
    selectManagementPlans(state, sale?.crop_variety_sale),
  );
```

When editing, the crops for existing sale would show up, along with crops that have current and planned plans. When adding, only the current and planned ones would show up. I think that's the desired behavior?

**Comment by Duncan-Brain** [comment]
I think it looks correct to me adding the existing sale crop to the options, if none exists (new sale) none is added.

My only comment might be that it could be good to keep the creation of selectors in the slice.

**Comment by navDhammu** [comment]
@Duncan-Brain We can put the selector in the slice but I just kept in the file because it was very specfic to the crop sale and not really reusable. Also I couldn't come up with a name that doesn't sound like a sentence - currentAndPlannedManagementPlansAndPlansWithCropSale?

**Review by Duncan-Brain — APPROVED** [review]

**Comment by navDhammu** [comment]
@Duncan-Brain `managementPlanByCropIdSelector` uses managementPlanSelector which filters out deleted plans so it wouldn't work if the user were to delete a crop plan associated with a historical sale. And I think a crop sale can have more than one crop as part of that sale if I'm not wrong?

**Comment by antsgar** [comment]
@navDhammu yup, that's the correct behavior! You're right, I was using a crop for testing that I thought no longer had active plans but it turns out that it did, sorry about that

**Review by antsgar — APPROVED** [review]

**Pull request merged**
